"""
Canonical Verified Curriculum Repository for Indian Educational Boards.
Strict Zero-Hallucination: Authentic curricula from CBSE, ICSE, and SCERT Telangana State Board.
"""

from typing import List, Dict, Any

CANONICAL_CURRICULUM: List[Dict[str, Any]] = [
    # =========================================================================
    # CBSE CURRICULUM
    # =========================================================================
    {
        "board": "CBSE",
        "state": None,
        "class_level": 10,
        "class_name": "Grade 10",
        "subject_code": "MATH10",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "CBSE Official Curriculum Guidelines 2026",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Real Numbers", "topic": "Fundamental Theorem of Arithmetic", "periods": 5, "seq": 1},
            {"unit": "Algebra", "chapter": "Polynomials", "topic": "Zeroes of a Polynomial & Coefficients", "periods": 6, "seq": 2},
            {"unit": "Algebra", "chapter": "Pair of Linear Equations", "topic": "Graphical & Algebraic Solution Methods", "periods": 8, "seq": 3},
            {"unit": "Algebra", "chapter": "Quadratic Equations", "topic": "Standard Form and Quadratic Formula", "periods": 7, "seq": 4},
            {"unit": "Algebra", "chapter": "Arithmetic Progressions", "topic": "nth Term and Sum of n Terms", "periods": 6, "seq": 5},
            {"unit": "Geometry", "chapter": "Triangles", "topic": "Similarity and Basic Proportionality Theorem", "periods": 9, "seq": 6},
            {"unit": "Coordinate Geometry", "chapter": "Coordinate Geometry", "topic": "Distance and Section Formulae", "periods": 6, "seq": 7},
            {"unit": "Trigonometry", "chapter": "Introduction to Trigonometry", "topic": "Trigonometric Ratios and Identities", "periods": 8, "seq": 8},
            {"unit": "Trigonometry", "chapter": "Some Applications of Trigonometry", "topic": "Heights and Distances", "periods": 6, "seq": 9},
            {"unit": "Geometry", "chapter": "Circles", "topic": "Tangents to a Circle from an External Point", "periods": 5, "seq": 10},
            {"unit": "Mensuration", "chapter": "Surface Areas and Volumes", "topic": "Combinations of Solids", "periods": 7, "seq": 11},
            {"unit": "Statistics & Probability", "chapter": "Statistics", "topic": "Mean, Median, and Mode of Grouped Data", "periods": 7, "seq": 12},
            {"unit": "Statistics & Probability", "chapter": "Probability", "topic": "Classical Definition of Probability", "periods": 4, "seq": 13},
        ]
    },
    {
        "board": "CBSE",
        "state": None,
        "class_level": 10,
        "class_name": "Grade 10",
        "subject_code": "SCI10",
        "subject_name": "Science",
        "academic_year_code": "2026-2027",
        "source": "CBSE Official Curriculum Guidelines 2026",
        "source_version": "2026.1",
        "items": [
            {"unit": "Chemical Substances", "chapter": "Chemical Reactions & Equations", "topic": "Types of Reactions & Oxidation/Reduction", "periods": 7, "seq": 1},
            {"unit": "Chemical Substances", "chapter": "Acids, Bases and Salts", "topic": "pH Scale & Properties of Common Salts", "periods": 8, "seq": 2},
            {"unit": "Chemical Substances", "chapter": "Metals and Non-metals", "topic": "Reactivity Series & Ionic Compounds", "periods": 8, "seq": 3},
            {"unit": "Chemical Substances", "chapter": "Carbon and Its Compounds", "topic": "Covalent Bonding & Functional Groups", "periods": 9, "seq": 4},
            {"unit": "World of Living", "chapter": "Life Processes", "topic": "Nutrition, Respiration, Transport & Excretion", "periods": 10, "seq": 5},
            {"unit": "World of Living", "chapter": "Control and Coordination", "topic": "Nervous System & Hormones in Animals", "periods": 7, "seq": 6},
            {"unit": "World of Living", "chapter": "How do Organisms Reproduce?", "topic": "Asexual and Sexual Reproduction", "periods": 8, "seq": 7},
            {"unit": "World of Living", "chapter": "Heredity and Evolution", "topic": "Mendel's Laws & Inheritance Patterns", "periods": 6, "seq": 8},
            {"unit": "Natural Phenomena", "chapter": "Light - Reflection and Refraction", "topic": "Spherical Mirrors & Lenses, Snell's Law", "periods": 9, "seq": 9},
            {"unit": "Natural Phenomena", "chapter": "Human Eye & Colorful World", "topic": "Structure of Eye, Defects & Dispersion", "periods": 6, "seq": 10},
            {"unit": "Effects of Current", "chapter": "Electricity", "topic": "Ohm's Law, Resistance in Series/Parallel", "periods": 9, "seq": 11},
            {"unit": "Effects of Current", "chapter": "Magnetic Effects of Electric Current", "topic": "Magnetic Fields, Solenoid & Motor Principle", "periods": 8, "seq": 12},
            {"unit": "Natural Resources", "chapter": "Our Environment", "topic": "Ecosystem, Food Chains & Waste Management", "periods": 5, "seq": 13},
        ]
    },
    {
        "board": "CBSE",
        "state": None,
        "class_level": 9,
        "class_name": "Grade 9",
        "subject_code": "MATH9",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "CBSE Official Curriculum Guidelines 2026",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Number Systems", "topic": "Irrational Numbers and Real Numbers", "periods": 7, "seq": 1},
            {"unit": "Algebra", "chapter": "Polynomials", "topic": "Remainder & Factor Theorems, Identities", "periods": 8, "seq": 2},
            {"unit": "Coordinate Geometry", "chapter": "Coordinate Geometry", "topic": "Cartesian Plane and Coordinates", "periods": 5, "seq": 3},
            {"unit": "Algebra", "chapter": "Linear Equations in Two Variables", "topic": "Graph of a Linear Equation", "periods": 6, "seq": 4},
            {"unit": "Geometry", "chapter": "Lines and Angles", "topic": "Pairs of Angles and Parallel Lines", "periods": 7, "seq": 5},
            {"unit": "Geometry", "chapter": "Triangles", "topic": "Congruence Criteria (SAS, ASA, SSS, RHS)", "periods": 8, "seq": 6},
            {"unit": "Geometry", "chapter": "Quadrilaterals", "topic": "Properties of Parallelograms & Mid-point", "periods": 7, "seq": 7},
            {"unit": "Geometry", "chapter": "Circles", "topic": "Chords and Angles Subtended by Arcs", "periods": 7, "seq": 8},
            {"unit": "Mensuration", "chapter": "Heron's Formula", "topic": "Area of Triangles using Heron's Formula", "periods": 5, "seq": 9},
            {"unit": "Mensuration", "chapter": "Surface Areas and Volumes", "topic": "Cones, Spheres and Hemispheres", "periods": 8, "seq": 10},
            {"unit": "Statistics", "chapter": "Statistics", "topic": "Bar Graphs, Histograms and Frequency Polygons", "periods": 6, "seq": 11},
        ]
    },
    {
        "board": "CBSE",
        "state": None,
        "class_level": 8,
        "class_name": "Grade 8",
        "subject_code": "CBSE_MATH_8",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "CBSE Official Curriculum Guidelines (cbseacademic.nic.in)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Rational Numbers", "topic": "Properties of Rational Numbers, Representation on Number Line", "periods": 6, "seq": 1},
            {"unit": "Algebra", "chapter": "Linear Equations in One Variable", "topic": "Solving Equations having the Variable on both Sides", "periods": 6, "seq": 2},
            {"unit": "Geometry", "chapter": "Understanding Quadrilaterals", "topic": "Polygons, Sum of the Measures of Exterior Angles", "periods": 6, "seq": 3},
            {"unit": "Data Handling", "chapter": "Data Handling", "topic": "Organising Data, Grouping Data, Circle Graph or Pie Chart", "periods": 6, "seq": 4},
            {"unit": "Number Systems", "chapter": "Squares and Square Roots", "topic": "Properties of Square Numbers, Finding Square Roots", "periods": 6, "seq": 5},
            {"unit": "Number Systems", "chapter": "Cubes and Cube Roots", "topic": "Cubes, Prime Factorisation Method for Cube Roots", "periods": 5, "seq": 6},
            {"unit": "Commercial Mathematics", "chapter": "Comparing Quantities", "topic": "Recalling Ratios and Percentages, Compound Interest", "periods": 7, "seq": 7},
            {"unit": "Algebra", "chapter": "Algebraic Expressions and Identities", "topic": "Monomials, Binomials, Polynomials, Standard Identities", "periods": 7, "seq": 8},
            {"unit": "Mensuration", "chapter": "Mensuration", "topic": "Area of Trapezium and General Quadrilateral, Surface Area & Volume", "periods": 7, "seq": 9},
            {"unit": "Algebra", "chapter": "Exponents and Powers", "topic": "Powers with Negative Exponents, Laws of Exponents", "periods": 5, "seq": 10},
            {"unit": "Arithmetic", "chapter": "Direct and Inverse Proportions", "topic": "Direct Proportion, Inverse Proportion", "periods": 5, "seq": 11},
            {"unit": "Algebra", "chapter": "Factorisation", "topic": "Common Factors, Factorisation by Regrouping Terms", "periods": 6, "seq": 12},
            {"unit": "Graphs", "chapter": "Introduction to Graphs", "topic": "A Bar Graph, A Pie Graph, Linear Graphs and Coordinates", "periods": 5, "seq": 13},
        ]
    },
    {
        "board": "CBSE",
        "state": None,
        "class_level": 8,
        "class_name": "Grade 8",
        "subject_code": "CBSE_SCI_8",
        "subject_name": "Science",
        "academic_year_code": "2026-2027",
        "source": "CBSE Official Curriculum Guidelines (cbseacademic.nic.in)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Food Production", "chapter": "Crop Production and Management", "topic": "Agricultural Practices, Basic Practices of Crop Production", "periods": 6, "seq": 1},
            {"unit": "Living World", "chapter": "Microorganisms: Friend and Foe", "topic": "Where do Microorganisms Live?, Friendly Microorganisms", "periods": 6, "seq": 2},
            {"unit": "Materials", "chapter": "Coal and Petroleum", "topic": "Coal, Petroleum, Refining, Natural Gas", "periods": 5, "seq": 3},
            {"unit": "Chemical Substances", "chapter": "Combustion and Flame", "topic": "What is Combustion?, How do We Control Fire?, Types of Combustion", "periods": 6, "seq": 4},
            {"unit": "Conservation", "chapter": "Conservation of Plants and Animals", "topic": "Deforestation and Its Causes, Biosphere Reserve", "periods": 6, "seq": 5},
            {"unit": "Living World", "chapter": "Reproduction in Animals", "topic": "Modes of Reproduction, Sexual Reproduction, Asexual Reproduction", "periods": 6, "seq": 6},
            {"unit": "Living World", "chapter": "Reaching the Age of Adolescence", "topic": "Adolescence and Puberty, Changes at Puberty, Hormones", "periods": 6, "seq": 7},
            {"unit": "Moving Things", "chapter": "Force and Pressure", "topic": "Force: A Push or a Pull, Contact Forces, Pressure", "periods": 7, "seq": 8},
            {"unit": "Moving Things", "chapter": "Friction", "topic": "Force of Friction, Factors affecting Friction, Friction: A Necessary Evil", "periods": 6, "seq": 9},
            {"unit": "Moving Things", "chapter": "Sound", "topic": "Sound is Produced by a Vibrating Body, Amplitude, Time Period and Frequency", "periods": 6, "seq": 10},
            {"unit": "Effects of Current", "chapter": "Chemical Effects of Electric Current", "topic": "Do Liquids Conduct Electricity?, Electroplating", "periods": 6, "seq": 11},
            {"unit": "Natural Phenomena", "chapter": "Some Natural Phenomena", "topic": "Lightning, Earthquakes, Protection against Earthquakes", "periods": 5, "seq": 12},
            {"unit": "Natural Phenomena", "chapter": "Light", "topic": "What Makes Things Visible, Laws of Reflection, Sunlight", "periods": 6, "seq": 13},
        ]
    },

    # =========================================================================
    # ICSE CURRICULUM
    # =========================================================================
    {
        "board": "ICSE",
        "state": None,
        "class_level": 10,
        "class_name": "Grade 10",
        "subject_code": "MATH10_ICSE",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "CISCE ICSE Curriculum 2026",
        "source_version": "2026.1",
        "items": [
            {"unit": "Commercial Mathematics", "chapter": "GST (Goods and Services Tax)", "topic": "Computation of CGST, SGST and IGST", "periods": 6, "seq": 1},
            {"unit": "Commercial Mathematics", "chapter": "Banking", "topic": "Recurring Deposit Accounts", "periods": 5, "seq": 2},
            {"unit": "Algebra", "chapter": "Linear Inequations", "topic": "Solution Sets on the Real Number Line", "periods": 5, "seq": 3},
            {"unit": "Algebra", "chapter": "Quadratic Equations", "topic": "Nature of Roots and Word Problems", "periods": 8, "seq": 4},
            {"unit": "Algebra", "chapter": "Ratio and Proportion", "topic": "Componendo and Dividendo Properties", "periods": 6, "seq": 5},
            {"unit": "Coordinate Geometry", "chapter": "Reflection and Coordinates", "topic": "Invariant Points and Section Formula", "periods": 6, "seq": 6},
            {"unit": "Geometry", "chapter": "Similarity", "topic": "Maps and Scale Factors", "periods": 7, "seq": 7},
            {"unit": "Geometry", "chapter": "Circles and Tangents", "topic": "Intersecting Chords and Tangent Properties", "periods": 8, "seq": 8},
            {"unit": "Mensuration", "chapter": "Cylinder, Cone and Sphere", "topic": "Surface Area and Volume Combinations", "periods": 8, "seq": 9},
            {"unit": "Trigonometry", "chapter": "Trigonometrical Identities & Tables", "topic": "Heights and Distances Applications", "periods": 8, "seq": 10},
            {"unit": "Statistics & Probability", "chapter": "Statistics & Ogives", "topic": "Histogram, Ogive and Quartiles", "periods": 7, "seq": 11},
            {"unit": "Statistics & Probability", "chapter": "Probability", "topic": "Simple Problems on Single Events", "periods": 4, "seq": 12},
        ]
    },
    {
        "board": "ICSE",
        "state": None,
        "class_level": 8,
        "class_name": "Grade 8",
        "subject_code": "ICSE_MATH_8",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "CISCE Curriculum for Middle School (cisce.org)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Rational Numbers", "topic": "Representation, Operations, and Word Problems", "periods": 6, "seq": 1},
            {"unit": "Number Systems", "chapter": "Exponents and Radicals", "topic": "Laws of Indices and Scientific Notation", "periods": 5, "seq": 2},
            {"unit": "Algebra", "chapter": "Algebraic Expressions & Identities", "topic": "Multiplication, Division, and Special Products", "periods": 7, "seq": 3},
            {"unit": "Algebra", "chapter": "Factorisation", "topic": "Grouping, Difference of Squares & Trinomials", "periods": 6, "seq": 4},
            {"unit": "Commercial Mathematics", "chapter": "Percentages and Applications", "topic": "Profit, Loss, Discount, Tax and Simple Interest", "periods": 7, "seq": 5},
            {"unit": "Geometry", "chapter": "Quadrilaterals and Polygons", "topic": "Angle Sum Property, Parallelograms & Special Quadrilaterals", "periods": 7, "seq": 6},
            {"unit": "Mensuration", "chapter": "Area of Plane Figures", "topic": "Trapezium, Rhombus, Polygons and Circle Sectors", "periods": 7, "seq": 7},
            {"unit": "Statistics", "chapter": "Data Handling & Probability", "topic": "Histograms, Frequency Polygons & Empirical Probability", "periods": 6, "seq": 8},
        ]
    },
    {
        "board": "ICSE",
        "state": None,
        "class_level": 8,
        "class_name": "Grade 8",
        "subject_code": "ICSE_PHY_8",
        "subject_name": "Physics",
        "academic_year_code": "2026-2027",
        "source": "CISCE Curriculum for Middle School (cisce.org)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Matter", "chapter": "Matter and Kinetic Theory", "topic": "Kinetic Molecular Theory and Change of State", "periods": 6, "seq": 1},
            {"unit": "Physical Quantities", "chapter": "Physical Quantities and Measurement", "topic": "Density of Regular & Irregular Solids, Relative Density", "periods": 6, "seq": 2},
            {"unit": "Mechanics", "chapter": "Force and Pressure", "topic": "Turning Effect of Force, Pressure in Fluids, Atmospheric Pressure", "periods": 7, "seq": 3},
            {"unit": "Energy", "chapter": "Energy and Work", "topic": "Kinetic & Potential Energy, Conservation of Energy", "periods": 6, "seq": 4},
            {"unit": "Optics", "chapter": "Light Energy", "topic": "Refraction at Plane Surfaces, Curved Mirrors & Dispersion", "periods": 7, "seq": 5},
            {"unit": "Heat", "chapter": "Heat Transfer", "topic": "Conduction, Convection, Radiation, Thermal Expansion", "periods": 6, "seq": 6},
            {"unit": "Acoustics", "chapter": "Sound Waves", "topic": "Propagation of Sound, Pitch, Loudness and Quality", "periods": 6, "seq": 7},
            {"unit": "Electricity", "chapter": "Electricity and Magnetism", "topic": "Static Electricity, Electric Current, Electromagnetism", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "ICSE",
        "state": None,
        "class_level": 8,
        "class_name": "Grade 8",
        "subject_code": "ICSE_CHEM_8",
        "subject_name": "Chemistry",
        "academic_year_code": "2026-2027",
        "source": "CISCE Curriculum for Middle School (cisce.org)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Matter", "chapter": "Matter and Chemical Composition", "topic": "Elements, Compounds, Mixtures & Separation Techniques", "periods": 6, "seq": 1},
            {"unit": "Atomic Structure", "chapter": "Physical and Chemical Changes", "topic": "Law of Conservation of Mass & Energy Changes", "periods": 6, "seq": 2},
            {"unit": "Atomic Structure", "chapter": "Elements, Compounds and Symbols", "topic": "Radicals, Valency, Chemical Formulae & Equations", "periods": 7, "seq": 3},
            {"unit": "Atomic Structure", "chapter": "Atomic Structure", "topic": "Subatomic Particles, Rutherford's & Bohr's Atomic Models", "periods": 7, "seq": 4},
            {"unit": "Atmosphere", "chapter": "Language of Chemistry", "topic": "Balancing Equations & Relative Molecular Mass", "periods": 6, "seq": 5},
            {"unit": "Chemical Reactions", "chapter": "Chemical Reactions", "topic": "Combination, Decomposition, Displacement & Double Decomposition", "periods": 7, "seq": 6},
            {"unit": "Atmosphere", "chapter": "Hydrogen & Water", "topic": "Preparation of Hydrogen, Water as Universal Solvent", "periods": 6, "seq": 7},
            {"unit": "Atmosphere", "chapter": "Carbon and Its Compounds", "topic": "Allotropes of Carbon, Carbon Monoxide and Carbon Dioxide", "periods": 7, "seq": 8},
        ]
    },

    # =========================================================================
    # STATE BOARDS (TELANGANA, KARNATAKA, MAHARASHTRA)
    # =========================================================================

    # ------------------ CLASS 10 (SSC) ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_MATH_10",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Real Numbers", "topic": "Euclid's Division Lemma & Fundamental Theorem of Arithmetic", "periods": 8, "seq": 1},
            {"unit": "Number Systems", "chapter": "Sets", "topic": "Basic Set Operations, Venn Diagrams and Disjoint Sets", "periods": 6, "seq": 2},
            {"unit": "Algebra", "chapter": "Polynomials", "topic": "Geometrical Meaning of Zeroes & Cubic Polynomials", "periods": 7, "seq": 3},
            {"unit": "Algebra", "chapter": "Pair of Linear Equations in Two Variables", "topic": "Graphical & Algebraic Methods of Solving Linear Equations", "periods": 9, "seq": 4},
            {"unit": "Algebra", "chapter": "Quadratic Equations", "topic": "Factorisation, Completing the Square & Nature of Roots", "periods": 8, "seq": 5},
            {"unit": "Algebra", "chapter": "Progressions", "topic": "Arithmetic and Geometric Progressions (AP & GP)", "periods": 9, "seq": 6},
            {"unit": "Coordinate Geometry", "chapter": "Coordinate Geometry", "topic": "Distance, Section Formula, Mid-point & Area of Triangle", "periods": 8, "seq": 7},
            {"unit": "Geometry", "chapter": "Similar Triangles", "topic": "Basic Proportionality Theorem, Criteria for Similarity & Pythagoras Theorem", "periods": 10, "seq": 8},
            {"unit": "Geometry", "chapter": "Tangents and Secants to a Circle", "topic": "Tangent Properties, Tangent Lengths from External Point & Sector Area", "periods": 8, "seq": 9},
            {"unit": "Mensuration", "chapter": "Mensuration", "topic": "Surface Areas & Volumes of Combinations of Solids", "periods": 9, "seq": 10},
            {"unit": "Trigonometry", "chapter": "Trigonometry", "topic": "Trigonometric Ratios, Values of Specific Angles & Identities", "periods": 9, "seq": 11},
            {"unit": "Trigonometry", "chapter": "Applications of Trigonometry", "topic": "Heights and Distances, Angle of Elevation and Depression", "periods": 7, "seq": 12},
            {"unit": "Probability & Statistics", "chapter": "Probability", "topic": "Theoretical Probability, Mutually Exclusive & Independent Events", "periods": 5, "seq": 13},
            {"unit": "Probability & Statistics", "chapter": "Statistics", "topic": "Mean, Median, Mode of Grouped Data & Ogive Curves", "periods": 8, "seq": 14},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_SCI_10",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Physical Science", "chapter": "Chemical Reactions and Equations", "topic": "Types of Reactions, Oxidation, Reduction, Corrosion & Rancidity", "periods": 8, "seq": 1},
            {"unit": "Physical Science", "chapter": "Acids, Bases and Salts", "topic": "Chemical Properties of Acids/Bases, pH Scale, Common Salts", "periods": 8, "seq": 2},
            {"unit": "Physical Science", "chapter": "Refraction of Light at Plane Surfaces", "topic": "Refractive Index, Snell's Law & Total Internal Reflection", "periods": 8, "seq": 3},
            {"unit": "Physical Science", "chapter": "Refraction of Light at Curved Surfaces", "topic": "Lens Formula, Sign Convention, Magnification & Power", "periods": 8, "seq": 4},
            {"unit": "Physical Science", "chapter": "Human Eye and Colourful World", "topic": "Defects of Vision, Prism Dispersion, Atmospheric Refraction & Scattering", "periods": 7, "seq": 5},
            {"unit": "Physical Science", "chapter": "Structure of Atom", "topic": "Bohr-Sommerfeld Model, Quantum Numbers & Electronic Configuration", "periods": 9, "seq": 6},
            {"unit": "Physical Science", "chapter": "Classification of Elements - Periodic Table", "topic": "Modern Periodic Table, Periodic Trends & Valency", "periods": 8, "seq": 7},
            {"unit": "Physical Science", "chapter": "Chemical Bonding", "topic": "Ionic & Covalent Bonding, Octet Rule, VSEPR Theory Shapes", "periods": 8, "seq": 8},
            {"unit": "Physical Science", "chapter": "Electric Current", "topic": "Ohm's Law, Resistivity, Series & Parallel Combinations, Joule Heating", "periods": 9, "seq": 9},
            {"unit": "Physical Science", "chapter": "Electromagnetism", "topic": "Magnetic Field, Oersted Experiment, Electromagnetic Induction, AC/DC Dynamo", "periods": 9, "seq": 10},
            {"unit": "Physical Science", "chapter": "Principles of Metallurgy", "topic": "Occurrence of Metals, Concentration, Extraction & Refining", "periods": 7, "seq": 11},
            {"unit": "Physical Science", "chapter": "Carbon and its Compounds", "topic": "Catenation, Homologous Series, Functional Groups & IUPAC Nomenclature", "periods": 9, "seq": 12},
            {"unit": "Biological Science", "chapter": "Nutrition - Food Supplying System", "topic": "Autotrophic Photosynthesis, Light/Dark Reactions, Human Digestion", "periods": 9, "seq": 13},
            {"unit": "Biological Science", "chapter": "Respiration - The Energy Producing System", "topic": "Aerobic and Anaerobic Respiration, Mechanism of Respiration in Humans", "periods": 8, "seq": 14},
            {"unit": "Biological Science", "chapter": "Transportation - The Circulatory System", "topic": "Internal Structure of Heart, Cardiac Cycle, Blood Vessels & Lymphatic System", "periods": 9, "seq": 15},
            {"unit": "Biological Science", "chapter": "Excretion - The Waste Disposing System", "topic": "Structure of Kidney and Nephron, Urine Formation Mechanism, Dialysis", "periods": 8, "seq": 16},
            {"unit": "Biological Science", "chapter": "Coordination - The Linking System", "topic": "Structure of Neuron, Synapse, Central Nervous System & Endocrine Glands", "periods": 9, "seq": 17},
            {"unit": "Biological Science", "chapter": "Reproduction - The Generating System", "topic": "Asexual Reproduction, Sexual Reproduction in Flowering Plants & Humans", "periods": 9, "seq": 18},
            {"unit": "Biological Science", "chapter": "Heredity - From Parent to Progeny", "topic": "Mendel's Laws of Inheritance, Sex Determination in Humans & Evolution", "periods": 8, "seq": 19},
            {"unit": "Biological Science", "chapter": "Our Environment - Our Concern", "topic": "Ecosystem, Energy Flow, Trophic Levels, Biological Magnification", "periods": 6, "seq": 20},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_SOC_10",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Resources & Development", "chapter": "India: Relief Features", "topic": "Geological Background, Himalayas, Indo-Gangetic Plains & Peninsular Plateau", "periods": 8, "seq": 1},
            {"unit": "Resources & Development", "chapter": "Ideas of Development", "topic": "Income and Other Goals, Human Development Report & Public Facilities", "periods": 7, "seq": 2},
            {"unit": "Production & Livelihood", "chapter": "Production and Employment", "topic": "Sectors of Economy, GDP Calculation, Organised and Unorganised Sectors", "periods": 8, "seq": 3},
            {"unit": "Environment & People", "chapter": "Climate of India", "topic": "Factors Influencing Climate, Mechanism of Monsoon, Western Disturbances", "periods": 7, "seq": 4},
            {"unit": "Environment & People", "chapter": "Indian Rivers and Water Resources", "topic": "Himalayan and Peninsular River Systems, Ground Water Inflow & Scarcity", "periods": 8, "seq": 5},
            {"unit": "Environment & People", "chapter": "The People - Population", "topic": "Census Data, Population Growth, Age Structure, Sex Ratio & Literacy", "periods": 7, "seq": 6},
            {"unit": "Globalisation & Equity", "chapter": "Globalisation", "topic": "Multinational Corporations (MNCs), Foreign Trade, WTO & Market Integration", "periods": 8, "seq": 7},
            {"unit": "Globalisation & Equity", "chapter": "Food Security", "topic": "Food Production, Availability, PDS Mechanism, Nutrition Levels in Telangana", "periods": 7, "seq": 8},
            {"unit": "Contemporary World", "chapter": "The World Between the World Wars", "topic": "Causes of WWI, Treaty of Versailles, Russian Revolution & Rise of Fascism", "periods": 9, "seq": 9},
            {"unit": "National Movement", "chapter": "National Movement in India - Partition & Independence", "topic": "Quit India Movement, Subhash Chandra Bose & INA, Partition & Integration", "periods": 9, "seq": 10},
            {"unit": "Indian Polity", "chapter": "The Making of Independent India's Constitution", "topic": "Constituent Assembly Debates, Preamble, Basic Principles & Federalism", "periods": 8, "seq": 11},
            {"unit": "Telangana State Formation", "chapter": "The Movement for the Formation of Telangana State", "topic": "Gentlemen's Agreement, 1969 Agitation, Million March & Telangana Act 2014", "periods": 10, "seq": 12},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_ENG_10",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Personality Development", "chapter": "Attitude is Altitude", "topic": "Reading Comprehension, Biography of Nick Vujicic, Vocabulary & Idioms", "periods": 7, "seq": 1},
            {"unit": "Wit and Humour", "chapter": "The Dear Departed", "topic": "Dramatic Dialogue, Character Study, Phrasal Verbs & Irony", "periods": 8, "seq": 2},
            {"unit": "Human Relations", "chapter": "The Journey", "topic": "Narrative Prose, Rural-Urban Contrast, Direct & Indirect Speech", "periods": 8, "seq": 3},
            {"unit": "Films and Theatre", "chapter": "Rendezvous with Ray", "topic": "Appreciation of Cinema, Satyajit Ray's Artistry & Passive Voice", "periods": 7, "seq": 4},
            {"unit": "Social Issues", "chapter": "The Storeyed House", "topic": "Dalit Literature, Caste Discrimination, Cohesion & Discourse Markers", "periods": 8, "seq": 5},
            {"unit": "Bio-Diversity", "chapter": "Environment & Conservation", "topic": "Wangari Maathai Interview, Green Belt Movement & Environmental Vocabulary", "periods": 7, "seq": 6},
            {"unit": "Nation and Diversity", "chapter": "My Childhood", "topic": "A.P.J. Abdul Kalam's Memoir, Communal Harmony & Relative Clauses", "periods": 8, "seq": 7},
            {"unit": "Human Rights", "chapter": "Jamaican Fragment", "topic": "Prejudice, Universal Brotherhood, Compound Sentences & Formal Writing", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_TEL_10",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Pracheena Kavitvam", "chapter": "Danaseelam", "topic": "Bammera Pothana, Bhagavatha Padya Bhavam & Tatparyam", "periods": 8, "seq": 1},
            {"unit": "Aadhunika Kavitvam", "chapter": "Veera Telangana", "topic": "Dasharathi Krishnamacharya, Porata Kavitvam & Bhasha Soundaryam", "periods": 8, "seq": 2},
            {"unit": "Galpika & Katha", "chapter": "Kothabata", "topic": "Paka Durganadha Shastri, Telangana Bhasha mariyu Gramina Jeevitam", "periods": 8, "seq": 3},
            {"unit": "Nagara Kavitvam", "chapter": "Nagarageetham", "topic": "Alishetty Prabhakar, Adhunika Samajam & Manava Sambandhalu", "periods": 7, "seq": 4},
            {"unit": "Neethi Sahityam", "chapter": "Shataka Madhurima", "topic": "Sumati, Vemana, Bharthruhari Subhashitalu & Naitika Viluvalu", "periods": 8, "seq": 5},
            {"unit": "Telangana Vaibhavam", "chapter": "Lakshya Siddhi", "topic": "Telangana Rashtra Sadhanalo Prajala Patra & Samskruthika Chaitanyam", "periods": 8, "seq": 6},
            {"unit": "Charitra & Vyakthitvam", "chapter": "Jeevitha Charitralu", "topic": "Telangana Praja Nayakulu, Kaloji & Prof. Jayashankar", "periods": 7, "seq": 7},
            {"unit": "Vyakaranam", "chapter": "Vyakaranam & Chandassu", "topic": "Sandhulu, Samasalu, Alankaralu, Utpalamala, Champakamala Chandassu", "periods": 10, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 10,
        "class_name": "Class 10",
        "subject_code": "TS_HIN_10",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Kavya", "chapter": "Baraste Badal", "topic": "Sumitranandan Pant, Prakriti Soundarya, Kavita Bhaav & Shabdarth", "periods": 7, "seq": 1},
            {"unit": "Kahani", "chapter": "Eidgah", "topic": "Munshi Premchand, Hamid Aur Ameena Ka Vatsalya, Naitikta", "periods": 8, "seq": 2},
            {"unit": "Kavya", "chapter": "Kan-Kan Ka Adhikari", "topic": "Ramdhari Singh Dinkar, Shram Ka Mahatva, Samajik Nyay", "periods": 7, "seq": 3},
            {"unit": "Nibandh", "chapter": "Lokgeet", "topic": "Bhagwath Sharan Upadhyay, Lok Sanskriti, Vividh Pranton Ke Geet", "periods": 7, "seq": 4},
            {"unit": "Bhasha Vignan", "chapter": "Antarrashtriya Star Par Hindi", "topic": "Hindi Bhasha Ki Upayogita, Rajbhasha Ka Swaroop Aur Mahatva", "periods": 7, "seq": 5},
            {"unit": "Pracheen Kavya", "chapter": "Bhakti Pad", "topic": "Raidas Aur Meerabai Ke Pad, Ishwar Bhakti, Bhaavartha", "periods": 8, "seq": 6},
            {"unit": "Natak & Ekanki", "chapter": "Swarajya Ki Neev", "topic": "Vishnu Prabhakar, Rani Laxmibai Ka Balidan, Deshbhakti", "periods": 7, "seq": 7},
            {"unit": "Vyakaran", "chapter": "Vyakaran & Rachana", "topic": "Karak, Kaal, Vakya Parivartan, Samas, Muhavare & Patra Lekhan", "periods": 9, "seq": 8},
        ]
    },

    # ------------------ CLASS 9 ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_MATH_9",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Real Numbers", "topic": "Rational and Irrational Numbers, Laws of Exponents & Radicals", "periods": 8, "seq": 1},
            {"unit": "Algebra", "chapter": "Polynomials and Factorisation", "topic": "Remainder Theorem, Factor Theorem & Algebraic Identities", "periods": 9, "seq": 2},
            {"unit": "Algebra", "chapter": "Linear Equations in Two Variables", "topic": "Standard Form, Solutions of Linear Equations & Graph Plotting", "periods": 8, "seq": 3},
            {"unit": "Coordinate Geometry", "chapter": "Coordinate Geometry", "topic": "Cartesian Coordinate System, Abscissa and Ordinate", "periods": 6, "seq": 4},
            {"unit": "Geometry", "chapter": "Lines and Angles", "topic": "Pairs of Angles, Transversal Properties & Parallel Lines", "periods": 8, "seq": 5},
            {"unit": "Geometry", "chapter": "Triangles", "topic": "Congruence Criteria (SAS, ASA, SSS, RHS) & Inequalities in a Triangle", "periods": 9, "seq": 6},
            {"unit": "Geometry", "chapter": "Quadrilaterals", "topic": "Types of Quadrilaterals, Properties of Parallelogram & Mid-point Theorem", "periods": 8, "seq": 7},
            {"unit": "Geometry", "chapter": "Circles", "topic": "Chords, Perpendicular from Centre & Angles Subtended by Arcs", "periods": 8, "seq": 8},
            {"unit": "Mensuration", "chapter": "Surface Areas and Volumes", "topic": "Surface Area & Volume of Cubes, Cuboids, Cylinders & Cones", "periods": 9, "seq": 9},
            {"unit": "Probability & Statistics", "chapter": "Statistics", "topic": "Collection of Data, Frequency Distribution & Bar Graphs", "periods": 7, "seq": 10},
            {"unit": "Probability & Statistics", "chapter": "Probability", "topic": "Experimental Approach to Probability & Empirical Trials", "periods": 5, "seq": 11},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_SCI_9",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Matter & States", "chapter": "Matter Around Us", "topic": "States of Matter, Evaporation, Latent Heat & Diffusion", "periods": 8, "seq": 1},
            {"unit": "Kinematics", "chapter": "Motion", "topic": "Distance, Displacement, Speed, Velocity, Acceleration & Graphs", "periods": 8, "seq": 2},
            {"unit": "Dynamics", "chapter": "Laws of Motion", "topic": "Newton's Three Laws of Motion, Inertia, Momentum & Conservation", "periods": 9, "seq": 3},
            {"unit": "Gravity", "chapter": "Gravitation", "topic": "Universal Law of Gravitation, Free Fall, Mass, Weight & Buoyancy", "periods": 8, "seq": 4},
            {"unit": "Energy", "chapter": "Work and Energy", "topic": "Scientific Concept of Work, Kinetic & Potential Energy, Conservation", "periods": 8, "seq": 5},
            {"unit": "Waves", "chapter": "Sound", "topic": "Production and Propagation of Sound, Speed of Sound, Ultrasound & Human Ear", "periods": 8, "seq": 6},
            {"unit": "Atoms", "chapter": "Atoms and Molecules", "topic": "Laws of Chemical Combination, Dalton's Atomic Theory, Mole Concept", "periods": 9, "seq": 7},
            {"unit": "Cell Biology", "chapter": "Cell - Basic Unit of Life", "topic": "Plant and Animal Cell Structure, Organelles & Plasma Membrane", "periods": 9, "seq": 8},
            {"unit": "Cell Biology", "chapter": "Tissues", "topic": "Meristematic, Permanent Plant Tissues & Animal Tissues (Epithelial, Muscular)", "periods": 9, "seq": 9},
            {"unit": "Health", "chapter": "Why Do We Fall Ill?", "topic": "Health and Disease, Infectious Agents, Means of Spread & Immunisation", "periods": 7, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_SOC_9",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "The Earth", "chapter": "Our Earth", "topic": "Earth's Origin, Latitudes and Longitudes, Grid System & Rotation", "periods": 7, "seq": 1},
            {"unit": "Natural Realms", "chapter": "Natural Realms of the Earth", "topic": "Lithosphere, Continental Drift, Plate Tectonics & Internal Forces", "periods": 8, "seq": 2},
            {"unit": "Natural Realms", "chapter": "Hydrosphere and Atmosphere", "topic": "Water Cycle, Ocean Relief, Atmospheric Layers & Atmospheric Pressure", "periods": 8, "seq": 3},
            {"unit": "Economy & Agriculture", "chapter": "Agriculture in India", "topic": "Types of Farming, Cropping Seasons, Major Crops & Agricultural Challenges", "periods": 8, "seq": 4},
            {"unit": "Economy & Industry", "chapter": "Industries in India", "topic": "Agro-based Industries, Mineral-based Industries & Industrial Pollution", "periods": 8, "seq": 5},
            {"unit": "Political System", "chapter": "Democratic Government", "topic": "Features of Democracy, Separation of Powers & Rule of Law", "periods": 7, "seq": 6},
            {"unit": "Indian Polity", "chapter": "Indian Constitution", "topic": "Fundamental Rights, Directive Principles of State Policy & Preamble", "periods": 8, "seq": 7},
            {"unit": "Telangana Heritage", "chapter": "Telangana Heritage and Culture", "topic": "Kakatiya Architecture, Ramappa Temple, Warangal Fort & Bathukamma", "periods": 9, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_ENG_9",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Humour", "chapter": "The Snake and the Mirror", "topic": "Irony and Self-Observation, Adjectives & Complex Sentences", "periods": 8, "seq": 1},
            {"unit": "Games and Sports", "chapter": "True Height", "topic": "Perseverance in Athletics, Vocabulary & Modal Auxiliaries", "periods": 8, "seq": 2},
            {"unit": "School Life", "chapter": "Swami and Friends", "topic": "R.K. Narayan's Malgudi Days, Childhood Conflicts & Direct Speech", "periods": 8, "seq": 3},
            {"unit": "Environment", "chapter": "What is a Man without the Beasts?", "topic": "Chief Seattle's Speech, Ecological Interdependence & Conjunctions", "periods": 7, "seq": 4},
            {"unit": "Art and Culture", "chapter": "The Story of Ikat", "topic": "Pochampally Weaving Art, Telangana Handlooms & Passive Voice", "periods": 8, "seq": 5},
            {"unit": "Freedom", "chapter": "A Havoc of Flood", "topic": "Disaster Response, Community Resilience & Report Writing", "periods": 7, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_TEL_9",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Neethi Sahityam", "chapter": "Dharma Bodha", "topic": "Mahabharata Kavitvam, Dharmam mariyu Naitika Pravartana", "periods": 8, "seq": 1},
            {"unit": "Vyakthitvam", "chapter": "Prerana", "topic": "A.P.J. Abdul Kalam Jeevitham, Lakshya Sadhana & Vidyarthulu", "periods": 8, "seq": 2},
            {"unit": "Bhashabhimanam", "chapter": "Swabhasha", "topic": "Panuganti Lakshminarasimha Rao, Matrubhasha Vishishtatha", "periods": 8, "seq": 3},
            {"unit": "Telangana Chaitanyam", "chapter": "Telangana Vaibhavam", "topic": "Telangana Sahithi Murthulu, Janapada Kalalu & Samskruthi", "periods": 8, "seq": 4},
            {"unit": "Samaja Kavitvam", "chapter": "Chaitanyam", "topic": "Adhunika Kavitvam, Samaja Vikasam & Manava Viluvalu", "periods": 7, "seq": 5},
            {"unit": "Vyakaranam", "chapter": "Vyakaranam & Bhashamsalu", "topic": "Savarnadeergha Sandhi, Guna Sandhi, Tatpurusha Samasam, Alankaralu", "periods": 9, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 9,
        "class_name": "Class 9",
        "subject_code": "TS_HIN_9",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Deshbhakti", "chapter": "Jis Desh Mein Ganga Behti Hai", "topic": "Shailendra, Desh Prem Ki Bhawana, Bharat Ki Sanskritic Dharohar", "periods": 8, "seq": 1},
            {"unit": "Bal Manovigyan", "chapter": "Taare Zameen Par", "topic": "Bachhon Ki Prathibha, Shiksha Ka Sahaj Roop Aur Protsahan", "periods": 8, "seq": 2},
            {"unit": "Katha", "chapter": "Gillee Danda", "topic": "Munshi Premchand, Bachpan Ke Khel, Samanta Ki Bhawana", "periods": 8, "seq": 3},
            {"unit": "Khel", "chapter": "Football", "topic": "Khel Ka Mahatva, Ekata Aur Sahayog Ki Bhawana", "periods": 7, "seq": 4},
            {"unit": "Neethi", "chapter": "Rahim Ke Dohe", "topic": "Rahim, Jeevan Mulya, Sadbhavna Aur Vyavaharikta", "periods": 8, "seq": 5},
            {"unit": "Vyakaran", "chapter": "Vyakaran & Patra", "topic": "Kriya Bhed, Sangya, Sarvanam, Upsarg, Pratyay Aur Nibandh Lekhan", "periods": 9, "seq": 6},
        ]
    },

    # ------------------ CLASS 8 ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_MATH_8",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Number Systems", "chapter": "Rational Numbers", "topic": "Properties of Rational Numbers, Number Line Representation", "periods": 8, "seq": 1},
            {"unit": "Algebra", "chapter": "Linear Equations in One Variable", "topic": "Solving Linear Equations with Variables on Both Sides", "periods": 8, "seq": 2},
            {"unit": "Geometry", "chapter": "Understanding Quadrilaterals", "topic": "Polygons, Convex and Concave, Angle Sum Property", "periods": 8, "seq": 3},
            {"unit": "Geometry", "chapter": "Practical Geometry", "topic": "Construction of Quadrilaterals given Sides and Diagonals", "periods": 8, "seq": 4},
            {"unit": "Data Handling", "chapter": "Data Handling", "topic": "Frequency Tables, Histograms & Pie Charts", "periods": 7, "seq": 5},
            {"unit": "Number Operations", "chapter": "Squares and Square Roots", "topic": "Square Numbers, Prime Factorisation & Division Method", "periods": 8, "seq": 6},
            {"unit": "Arithmetic", "chapter": "Comparing Quantities", "topic": "Percentage, Profit and Loss, Compound Interest", "periods": 8, "seq": 7},
            {"unit": "Algebra", "chapter": "Algebraic Expressions and Identities", "topic": "Addition, Subtraction, Multiplication & Standard Identities", "periods": 8, "seq": 8},
            {"unit": "Mensuration", "chapter": "Mensuration", "topic": "Area of Trapezium, Surface Area of Cuboid & Cylinder", "periods": 8, "seq": 9},
            {"unit": "Algebra", "chapter": "Exponents and Powers", "topic": "Powers with Negative Exponents & Laws of Exponents", "periods": 7, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_SCI_8",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Mechanics", "chapter": "Force", "topic": "Types of Forces (Contact and Non-contact), Pressure", "periods": 8, "seq": 1},
            {"unit": "Mechanics", "chapter": "Friction", "topic": "Factors Affecting Friction, Advantages and Disadvantages of Friction", "periods": 8, "seq": 2},
            {"unit": "Materials", "chapter": "Synthetic Fibres and Plastics", "topic": "Types of Synthetic Fibres, Thermoplastics and Thermosetting Plastics", "periods": 7, "seq": 3},
            {"unit": "Chemistry", "chapter": "Metals and Non-Metals", "topic": "Physical and Chemical Properties of Metals & Non-metals", "periods": 8, "seq": 4},
            {"unit": "Fuels", "chapter": "Coal and Petroleum", "topic": "Fossil Fuels, Refining of Petroleum & Natural Gas", "periods": 7, "seq": 5},
            {"unit": "Energy", "chapter": "Combustion and Flame", "topic": "Conditions for Combustion, Fire Fighting & Structure of Flame", "periods": 8, "seq": 6},
            {"unit": "Biology", "chapter": "Cell - Structure and Functions", "topic": "Discovery of Cell, Cell Wall, Cytoplasm and Nucleus", "periods": 8, "seq": 7},
            {"unit": "Biology", "chapter": "Reproduction in Animals", "topic": "Sexual Reproduction, Fertilisation (Internal and External), Cloning", "periods": 8, "seq": 8},
            {"unit": "Physics", "chapter": "Sound", "topic": "Vibration as Cause of Sound, Amplitude, Frequency & Noise Pollution", "periods": 8, "seq": 9},
            {"unit": "Optics", "chapter": "Light", "topic": "Laws of Reflection, Regular & Diffused Reflection, Multiple Images", "periods": 8, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_SOC_8",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Geography", "chapter": "Reading and Making Maps", "topic": "Maps from Ancient to Modern Times, Scale, Projections & Symbols", "periods": 7, "seq": 1},
            {"unit": "Earth & Sun", "chapter": "Energy from the Sun", "topic": "Solar Radiation, Insolation, Temperature Inversion & Sun's Rays", "periods": 8, "seq": 2},
            {"unit": "Seasons", "chapter": "Earth Movements and Seasons", "topic": "Rotation, Revolution, Solstices, Equinoxes & Seasonal Changes", "periods": 8, "seq": 3},
            {"unit": "Forests", "chapter": "Forests: Using and Protecting Them", "topic": "Forest Types, Tribal Livelihoods, Forest Rights Act in Telangana", "periods": 8, "seq": 4},
            {"unit": "Economy", "chapter": "Minerals and Mining", "topic": "Singareni Collieries, Coal Mining in Godavari Valley, Environmental Impact", "periods": 8, "seq": 5},
            {"unit": "Banking", "chapter": "Money and Banking", "topic": "Evolution of Money, Commercial Banks, Loans & Financial Literacy", "periods": 8, "seq": 6},
            {"unit": "Telangana History", "chapter": "Veera Nari Rudrama Devi & Kakatiyas", "topic": "Queen Rudrama Devi's Rule, Administration & Irrigation Tanks", "periods": 9, "seq": 7},
            {"unit": "Disaster Management", "chapter": "Disaster Management", "topic": "Types of Disasters, Preparedness, Evacuation & Community First Aid", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_ENG_8",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Bravery", "chapter": "The Tsunami", "topic": "Natural Catastrophe, Animal Intuition, Survival & Phrasal Verbs", "periods": 8, "seq": 1},
            {"unit": "Freedom", "chapter": "Glimpses of the Past", "topic": "British Rule, 1857 Mutiny, Freedom Struggle & Discourse Markers", "periods": 8, "seq": 2},
            {"unit": "Adventure", "chapter": "The Summit Within", "topic": "Major H.P.S. Ahluwalia, Mt. Everest Ascent, Endurance & Will Power", "periods": 8, "seq": 3},
            {"unit": "Inspiration", "chapter": "A Visit to Cambridge", "topic": "Stephen Hawking Meeting, Disability Rights & Conjunctions", "periods": 8, "seq": 4},
            {"unit": "Humanitarianism", "chapter": "The Best Christmas Present in the World", "topic": "WWI Christmas Truce, Trench Warfare & Letter Writing", "periods": 8, "seq": 5},
            {"unit": "Grammar", "chapter": "Grammar & Composition", "topic": "Tenses, Reported Speech, Active-Passive Voice & Paragraph Writing", "periods": 8, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_TEL_8",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Pothana Kavitvam", "chapter": "Tyagaseelam", "topic": "Shibi Chakravarthi Katha, Tyagam & Dharma Parirakshana", "periods": 8, "seq": 1},
            {"unit": "Ramayana Sahityam", "chapter": "Samudrolanghanam", "topic": "Hanumantha Sahasam, Karyashoora Tatvam", "periods": 8, "seq": 2},
            {"unit": "Samajam", "chapter": "Manava Sambandhalu", "topic": "Kutumba Vyavastha, Prema & Apyayathalu", "periods": 8, "seq": 3},
            {"unit": "Palle Jeevitam", "chapter": "Telangana Pallelu", "topic": "Gramina Samskruthi, Vruthi Panulu & Habbaalu", "periods": 8, "seq": 4},
            {"unit": "Veera Charitra", "chapter": "Rani Rudrama Devi", "topic": "Kakatiya Veeratha, Rajyaparipalana & Nari Shakthi", "periods": 8, "seq": 5},
            {"unit": "Vyakaranam", "chapter": "Vyakaranam & Chandassu", "topic": "Vruddhi Sandhi, Yanadesha Sandhi, Dwandva Samasam, Padya Lakshanalu", "periods": 9, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "TS_HIN_8",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Prerana", "chapter": "Hum Honge Kamyab", "topic": "Aatmavishwas, Vishwa Shanti Ki Bhawana Aur Lakshya", "periods": 8, "seq": 1},
            {"unit": "Katha", "chapter": "Lakh Ki Chudiyan", "topic": "Badlu Ka Vyavahar, Hastashilp Aur Yantrik Yug Ka Asar", "periods": 8, "seq": 2},
            {"unit": "Vyangya", "chapter": "Bus Ki Yatra", "topic": "Harishankar Parsai, Hasya-Vyangya Aur Bus Ki Durdasha", "periods": 8, "seq": 3},
            {"unit": "Kavya", "chapter": "Deewano Ki Hasti", "topic": "Bhagwati Charan Verma, Mastmaula Jeevan Aur Desh Prem", "periods": 7, "seq": 4},
            {"unit": "Kavya", "chapter": "Bhagwan Ke Daakiye", "topic": "Ramdhari Singh Dinkar, Prakriti Ka Sandesh Aur Vishwa Bandhutva", "periods": 7, "seq": 5},
            {"unit": "Vyakaran", "chapter": "Vyakaran & Patra", "topic": "Visheshan, Kriya Visheshan, Vakya Bhed Aur Prarthana Patra", "periods": 8, "seq": 6},
        ]
    },

    # ------------------ CLASS 7 ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_MATH_7",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Integers", "chapter": "Integers", "topic": "Addition, Subtraction, Multiplication & Division of Integers", "periods": 8, "seq": 1},
            {"unit": "Fractions", "chapter": "Fractions and Decimals", "topic": "Multiplication & Division of Fractions and Decimals", "periods": 8, "seq": 2},
            {"unit": "Data", "chapter": "Data Handling", "topic": "Arithmetic Mean, Mode and Median of Unorganised Data", "periods": 7, "seq": 3},
            {"unit": "Equations", "chapter": "Simple Equations", "topic": "Setting up Equations and Solving Linear Equations", "periods": 8, "seq": 4},
            {"unit": "Geometry", "chapter": "Lines and Angles", "topic": "Complementary, Supplementary Angles & Parallel Line Transversal", "periods": 8, "seq": 5},
            {"unit": "Geometry", "chapter": "The Triangle and its Properties", "topic": "Medians, Altitudes, Exterior Angle Property & Angle Sum", "periods": 8, "seq": 6},
            {"unit": "Geometry", "chapter": "Congruence of Triangles", "topic": "Congruence Conditions of Triangles (SSS, SAS, ASA, RHS)", "periods": 8, "seq": 7},
            {"unit": "Arithmetic", "chapter": "Comparing Quantities", "topic": "Ratios, Proportions, Percentage & Simple Interest", "periods": 8, "seq": 8},
            {"unit": "Rational Numbers", "chapter": "Rational Numbers", "topic": "Positive and Negative Rational Numbers & Standard Form", "periods": 7, "seq": 9},
            {"unit": "Mensuration", "chapter": "Perimeter and Area", "topic": "Area of Parallelograms, Triangles and Circles", "periods": 8, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_SCI_7",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Plant Biology", "chapter": "Nutrition in Plants", "topic": "Autotrophs, Chlorophyll, Photosynthesis & Heterotrophic Plants", "periods": 8, "seq": 1},
            {"unit": "Animal Biology", "chapter": "Nutrition in Animals", "topic": "Human Digestive Canal, Ingestion, Absorption & Digestion in Ruminants", "periods": 8, "seq": 2},
            {"unit": "Heat", "chapter": "Heat", "topic": "Temperature Measurement, Conduction, Convection & Radiation", "periods": 8, "seq": 3},
            {"unit": "Chemistry", "chapter": "Acids, Bases and Salts", "topic": "Indicators (Litmus, Turmeric), Neutralisation in Daily Life", "periods": 8, "seq": 4},
            {"unit": "Changes", "chapter": "Physical and Chemical Changes", "topic": "Rusting of Iron, Crystallisation & Burning of Magnesium", "periods": 7, "seq": 5},
            {"unit": "Physiology", "chapter": "Respiration in Organisms", "topic": "Breathing Mechanism in Humans, Gills in Fish & Spiracles in Insects", "periods": 8, "seq": 6},
            {"unit": "Physiology", "chapter": "Transportation in Plants and Animals", "topic": "Circulatory System in Humans, Heartbeat, Xylem and Phloem in Plants", "periods": 8, "seq": 7},
            {"unit": "Reproduction", "chapter": "Reproduction in Plants", "topic": "Vegetative Propagation, Flowers as Reproductive Parts & Seed Dispersal", "periods": 8, "seq": 8},
            {"unit": "Mechanics", "chapter": "Motion and Time", "topic": "Speed Measurement, Simple Pendulum & Distance-Time Graphs", "periods": 8, "seq": 9},
            {"unit": "Optics", "chapter": "Light", "topic": "Rectilinear Propagation of Light, Plane Mirrors & Spherical Mirrors", "periods": 8, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_SOC_7",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Maps", "chapter": "Reading Maps of Different Kinds", "topic": "Physical, Political and Thematic Maps, Elevation & Contour Lines", "periods": 7, "seq": 1},
            {"unit": "Water", "chapter": "Rain and Rivers", "topic": "Monsoon, Catchment Areas, Floods in Krishna and Godavari Rivers", "periods": 8, "seq": 2},
            {"unit": "Water Resources", "chapter": "Tanks and Ground Water", "topic": "Mission Kakatiya, Chain-linked Tanks in Telangana, Water Table", "periods": 8, "seq": 3},
            {"unit": "Oceans", "chapter": "Oceans and Fishing", "topic": "Ocean Currents, Coastal Ecology & Fishing Community Livelihoods", "periods": 7, "seq": 4},
            {"unit": "World Geography", "chapter": "Europe", "topic": "Physical Features, Climate, Rhine River & Industrial Revolution", "periods": 8, "seq": 5},
            {"unit": "History", "chapter": "New Kings and Kingdoms", "topic": "Rashtrakutas, Cholas & Chalukyas in South India", "periods": 8, "seq": 6},
            {"unit": "History", "chapter": "The Mughal Empire", "topic": "Akbar's Policies, Mansabdari System & Architecture", "periods": 8, "seq": 7},
            {"unit": "Telangana Economy", "chapter": "Production and Trade in Telangana", "topic": "Handlooms of Gadwal & Pochampally, Rythu Bazars, Agriculture Market", "periods": 8, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_ENG_7",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Fable", "chapter": "The Town Mouse and Country Mouse", "topic": "Aesop's Fable, Contrast in Lifestyles & Degrees of Comparison", "periods": 8, "seq": 1},
            {"unit": "Friendship", "chapter": "The New School", "topic": "Adjustment to New Environment, Compassion & Prepositions", "periods": 8, "seq": 2},
            {"unit": "Sportsmanship", "chapter": "The Brave Little Bowler", "topic": "Cricket, Fair Play, Athletic Resilience & Adverbs", "periods": 7, "seq": 3},
            {"unit": "Nature", "chapter": "Plants and Animals", "topic": "Symbiotic Life, Ecosystem Care & Conjunctions", "periods": 7, "seq": 4},
            {"unit": "Travel", "chapter": "Travel and Tourism in Telangana", "topic": "Nagarjuna Sagar, Laknavaram Lake & Itinerary Writing", "periods": 8, "seq": 5},
            {"unit": "Culture", "chapter": "Art and Architecture", "topic": "Historical Monuments, Thousand Pillar Temple & Descriptive Writing", "periods": 8, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_TEL_7",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Neethi", "chapter": "Sthreedharmam", "topic": "Naitika Viluvalu, Mahilala Patra & Samajika Gauravam", "periods": 8, "seq": 1},
            {"unit": "Palle Jeevitam", "chapter": "Palle Prema", "topic": "Palletoori Andhalu, Gramina Sneham & Patalu", "periods": 8, "seq": 2},
            {"unit": "Dhairyam", "chapter": "Sahasam", "topic": "Saahasikula Kathalu, Kastalu Edurkovadam", "periods": 8, "seq": 3},
            {"unit": "Charitra", "chapter": "Telangana Charitra", "topic": "Telangana Kotalu, Shasanala Charitra & Punya Kshetralu", "periods": 8, "seq": 4},
            {"unit": "Subhashitalu", "chapter": "Shataka Sourabham", "topic": "Vemana, Dasarathi Shataka Padyalu & Tatparyalu", "periods": 8, "seq": 5},
            {"unit": "Vyakaranam", "chapter": "Vyakaranam & Bhashamsalu", "topic": "Utsaha Sandhi, Trika Sandhi, Karmadharaya Samasam, Chandassu", "periods": 8, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 7,
        "class_name": "Class 7",
        "subject_code": "TS_HIN_7",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Kavya", "chapter": "Hum Panchhi Unmukt Gagan Ke", "topic": "Shivamangal Singh Suman, Swatantrata Ki Chahat Aur Prakriti", "periods": 8, "seq": 1},
            {"unit": "Kahani", "chapter": "Dadi Maa", "topic": "Shivprasad Singh, Parivarik Prem, Mamta Aur Sanskar", "periods": 8, "seq": 2},
            {"unit": "Prakriti", "chapter": "Himalaya Ki Betiyan", "topic": "Nagarjun, Nadiyon Ka Maanavikaran Aur Sundarta", "periods": 8, "seq": 3},
            {"unit": "Kavya", "chapter": "Kathputli", "topic": "Bhawani Prasad Mishra, Swatantrata Ki Pukar Aur Atmanirbharta", "periods": 7, "seq": 4},
            {"unit": "Kahani", "chapter": "Mithaiwala", "topic": "Bhagwati Prasad Vajpayee, Vatsalya, Bachhon Ka Aakarshan", "periods": 8, "seq": 5},
            {"unit": "Vyakaran", "chapter": "Vyakaran & Bhasha", "topic": "Vachan, Ling, Karak, Vilom Shabd Aur Chhuti Ke Liye Aavedan", "periods": 8, "seq": 6},
        ]
    },

    # ------------------ CLASS 6 ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_MATH_6",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Numbers", "chapter": "Knowing Our Numbers", "topic": "Large Numbers, Indian & International System of Numeration", "periods": 8, "seq": 1},
            {"unit": "Numbers", "chapter": "Whole Numbers", "topic": "Properties of Whole Numbers, Number Line Addition & Multiplication", "periods": 8, "seq": 2},
            {"unit": "Number Theory", "chapter": "Playing with Numbers", "topic": "Factors, Multiples, Prime & Composite Numbers, HCF and LCM", "periods": 8, "seq": 3},
            {"unit": "Geometry", "chapter": "Basic Geometrical Ideas", "topic": "Points, Lines, Rays, Angles, Curves, Polygons and Circles", "periods": 8, "seq": 4},
            {"unit": "Integers", "chapter": "Integers", "topic": "Positive and Negative Numbers, Number Line Representation", "periods": 8, "seq": 5},
            {"unit": "Fractions", "chapter": "Fractions", "topic": "Proper, Improper and Mixed Fractions, Equivalent Fractions", "periods": 8, "seq": 6},
            {"unit": "Decimals", "chapter": "Decimals", "topic": "Place Value of Decimals, Money & Measurement Conversion", "periods": 7, "seq": 7},
            {"unit": "Data", "chapter": "Data Handling", "topic": "Tally Marks, Pictographs and Interpretation of Bar Graphs", "periods": 7, "seq": 8},
            {"unit": "Mensuration", "chapter": "Mensuration", "topic": "Perimeter of Rectangle and Regular Shapes, Area of Rectangle", "periods": 8, "seq": 9},
            {"unit": "Ratios", "chapter": "Ratio and Proportion", "topic": "Concept of Ratio, Proportion and Unitary Method", "periods": 8, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_SCI_6",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Food", "chapter": "Food: Where Does It Come From?", "topic": "Plant and Animal Food Sources, Herbivores, Carnivores & Omnivores", "periods": 7, "seq": 1},
            {"unit": "Nutrition", "chapter": "Components of Food", "topic": "Carbohydrates, Fats, Proteins, Vitamins, Minerals & Balanced Diet", "periods": 8, "seq": 2},
            {"unit": "Materials", "chapter": "Fibre to Fabric", "topic": "Natural and Synthetic Fibres, Cotton Ginning, Spinning and Weaving", "periods": 8, "seq": 3},
            {"unit": "Materials", "chapter": "Sorting Materials into Groups", "topic": "Properties: Appearance, Hardness, Solubility & Transparency", "periods": 7, "seq": 4},
            {"unit": "Chemistry", "chapter": "Separation of Substances", "topic": "Handpicking, Winnowing, Sieving, Sedimentation, Decantation & Filtration", "periods": 8, "seq": 5},
            {"unit": "Botany", "chapter": "Getting to Know Plants", "topic": "Herbs, Shrubs, Trees, Leaf Venation, Root Systems & Flower Parts", "periods": 8, "seq": 6},
            {"unit": "Zoology", "chapter": "Body Movements", "topic": "Human Skeleton, Joints (Ball & Socket, Hinge), Gait of Animals", "periods": 8, "seq": 7},
            {"unit": "Ecology", "chapter": "Living Organisms & Their Surroundings", "topic": "Habitats (Terrestrial, Aquatic), Adaptations in Desert and Ocean", "periods": 8, "seq": 8},
            {"unit": "Optics", "chapter": "Light, Shadows and Reflections", "topic": "Transparent, Translucent, Opaque Objects, Formation of Shadows", "periods": 8, "seq": 9},
            {"unit": "Electricity", "chapter": "Electricity and Circuits", "topic": "Electric Cell, Switch, Closed and Open Circuits, Conductors and Insulators", "periods": 8, "seq": 10},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_SOC_6",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Geography", "chapter": "Reading Maps", "topic": "Cardinal Directions, Symbols, Scale & Sketch Maps", "periods": 7, "seq": 1},
            {"unit": "Earth", "chapter": "Globe - Model of the Earth", "topic": "Equator, Hemispheres, Latitudes, Longitudes & Time Zones", "periods": 8, "seq": 2},
            {"unit": "Landforms", "chapter": "Land Forms of Telangana", "topic": "Telangana Plateau, Hills, Plains & River Valleys", "periods": 8, "seq": 3},
            {"unit": "Village Study", "chapter": "A Village in Krishna Delta", "topic": "Village Penamakuru, Farming, Paddy Cultivation, Irrigation", "periods": 8, "seq": 4},
            {"unit": "Early Humans", "chapter": "From Gathering to Growing Food", "topic": "Hunter-Gatherers, Rock Paintings, Beginning of Farming & Herding", "periods": 8, "seq": 5},
            {"unit": "Civilizations", "chapter": "Early Civilizations", "topic": "Indus Valley Civilization, Town Planning, Great Bath, Seals & Crafts", "periods": 8, "seq": 6},
            {"unit": "Kingdoms", "chapter": "Kingdoms and Empires", "topic": "Mahajanapadas, Mauryan Empire, Ashoka's Dhamma & Inscriptions", "periods": 8, "seq": 7},
            {"unit": "Local Government", "chapter": "Village Panchayat and Municipalities", "topic": "Gram Sabha, Sarpanch, Local Governance in Telangana Villages", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_ENG_6",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Harmony", "chapter": "Peace and Harmony", "topic": "Forest Animals Fable, Unity, Antonyms & Subject-Verb Agreement", "periods": 8, "seq": 1},
            {"unit": "Wit", "chapter": "The Clever Tenali Raman", "topic": "Court of Krishnadevaraya, Presence of Mind & Punctuations", "periods": 8, "seq": 2},
            {"unit": "Folklore", "chapter": "A Golden Fish", "topic": "Folk Tales, Greed vs Contentment & Pronouns", "periods": 7, "seq": 3},
            {"unit": "Animals", "chapter": "Animals and Birds", "topic": "Wildlife Protection, Bird Habitats & Simple Past Tense", "periods": 8, "seq": 4},
            {"unit": "Sports", "chapter": "Nature and Sports", "topic": "Outdoor Games, Physical Fitness & Imperative Sentences", "periods": 7, "seq": 5},
            {"unit": "Heritage", "chapter": "Our Heritage", "topic": "Historical Monuments, Forts of Telangana & Story Writing", "periods": 8, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_TEL_6",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Prematho", "chapter": "Amma Vodi", "topic": "Talli Prema, Geyam, Bhavam & Matrubhasha Gauravam", "periods": 8, "seq": 1},
            {"unit": "Sneham", "chapter": "Sneham", "topic": "Mitrula Sneham, Sahayam Chese Gunam & Katha", "periods": 8, "seq": 2},
            {"unit": "Palle Jeevitam", "chapter": "Palletooru", "topic": "Palle Andalu, Rythula Srama & Janapada Patalu", "periods": 8, "seq": 3},
            {"unit": "Samskruthi", "chapter": "Telangana Samskruthi", "topic": "Bathukamma, Bonalu, Telangana Pandugala Vishishtatha", "periods": 8, "seq": 4},
            {"unit": "Neethi", "chapter": "Subhashitalu", "topic": "Neethi Padyalu, Satyam, Dharmam & Sadgunalu", "periods": 8, "seq": 5},
            {"unit": "Vyakaranam", "chapter": "Vyakaranam & Bhashamsalu", "topic": "Varnamala, Achulu, Hallulu, Guninthalu, Dvitva mariyu Samyuktaksharalu", "periods": 8, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 6,
        "class_name": "Class 6",
        "subject_code": "TS_HIN_6",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Kavya", "chapter": "Vah Chidiya Jo", "topic": "Kedarnath Agarwal, Chidiya Ki Madhur Aawaz Aur Santosh", "periods": 8, "seq": 1},
            {"unit": "Sansmaran", "chapter": "Bachpan", "topic": "Krishna Sobti, Bachpan Ki Yadein Aur Badlav", "periods": 8, "seq": 2},
            {"unit": "Kahani", "chapter": "Nadaan Dost", "topic": "Premchand, Chidiya Ke Ande, Nadani Aur Mamta", "periods": 8, "seq": 3},
            {"unit": "Kavya", "chapter": "Chand Se Thodi Si Gappein", "topic": "Shamsher Bahadur Singh, Balak Ki Kalpana Aur Chand", "periods": 7, "seq": 4},
            {"unit": "Nibandh", "chapter": "Aksharon Ka Mahatva", "topic": "Gunakar Mule, Lipi Ki Khoj Aur Manav Vikas", "periods": 8, "seq": 5},
            {"unit": "Vyakaran", "chapter": "Vyakaran & Abhyas", "topic": "Varnamala, Matra Parichay, Sangya, Vachan Aur Saral Vakya", "periods": 8, "seq": 6},
        ]
    },

    # ------------------ CLASS 5 ------------------
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_MATH_5",
        "subject_name": "Mathematics",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Numbers", "chapter": "Large Numbers & Place Value", "topic": "5 and 6 Digit Numbers, Place Value and Expanded Form", "periods": 7, "seq": 1},
            {"unit": "Operations", "chapter": "Addition and Subtraction", "topic": "Multi-digit Addition and Subtraction with Regrouping", "periods": 7, "seq": 2},
            {"unit": "Operations", "chapter": "Multiplication and Division", "topic": "Multiplication by 2-digit Numbers and Long Division", "periods": 8, "seq": 3},
            {"unit": "Factors", "chapter": "Factors and Multiples", "topic": "Prime Numbers, Factor Trees and Simple Multiples", "periods": 7, "seq": 4},
            {"unit": "Fractions", "chapter": "Fractions", "topic": "Fraction Parts of a Whole, Half, One-fourth & Comparison", "periods": 7, "seq": 5},
            {"unit": "Geometry", "chapter": "Geometry & Shapes", "topic": "2D and 3D Shapes, Angles (Right, Acute, Obtuse) & Symmetry", "periods": 7, "seq": 6},
            {"unit": "Measurement", "chapter": "Measurement of Length, Weight & Capacity", "topic": "Metres, Kilograms, Litres and Practical Conversions", "periods": 7, "seq": 7},
            {"unit": "Area", "chapter": "Perimeter and Area", "topic": "Perimeter of Polygons and Square Grid Area Counting", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_SCI_5",
        "subject_name": "General Science",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "My Family", "chapter": "My Family and Relationships", "topic": "Family Tree, Genetic Traits, Hereditary Characteristics & Values", "periods": 6, "seq": 1},
            {"unit": "Health", "chapter": "Our Body Parts & Health", "topic": "Sense Organs, Cleanliness, Dental Hygiene & Good Habits", "periods": 7, "seq": 2},
            {"unit": "Food", "chapter": "Food and Nutrition", "topic": "Components of Healthy Food, Spoilage, Preservation & Traditional Foods", "periods": 7, "seq": 3},
            {"unit": "Flora", "chapter": "Plants around Us", "topic": "Types of Plants, Parts of Plants, Leaf Shapes & Uses of Herbs", "periods": 7, "seq": 4},
            {"unit": "Fauna", "chapter": "Animals and Their Homes", "topic": "Shelter of Animals, Animal Behavior, Endangered Animals of Telangana", "periods": 7, "seq": 5},
            {"unit": "Natural Resources", "chapter": "Water - Sources and Uses", "topic": "Sources of Water, Water Purification, Rainwater Harvesting", "periods": 7, "seq": 6},
            {"unit": "Atmosphere", "chapter": "Air and Weather", "topic": "Properties of Air, Wind Direction, Seasons & Weather Changes", "periods": 6, "seq": 7},
            {"unit": "Telangana Environment", "chapter": "Telangana Environment & Forests", "topic": "Nallamala Forests, State Tree (Jammi), Bird (Palapitta) & Wildlife", "periods": 7, "seq": 8},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_SOC_5",
        "subject_name": "Social Studies",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Our Nation", "chapter": "Our Country India", "topic": "States and Capitals, National Symbols, Diversity in India", "periods": 7, "seq": 1},
            {"unit": "Cartography", "chapter": "Maps and Directions", "topic": "Four Directions, Reading a State Map of Telangana", "periods": 6, "seq": 2},
            {"unit": "Heritage", "chapter": "Our Heritage and Great Leaders", "topic": "Mahatma Gandhi, B.R. Ambedkar, Sarojini Naidu", "periods": 7, "seq": 3},
            {"unit": "Telangana Pride", "chapter": "Freedom Fighters of Telangana", "topic": "Komaram Bheem, Chakali Ilamma, Shoebullah Khan", "periods": 7, "seq": 4},
            {"unit": "Governance", "chapter": "Local Governance and Gram Panchayat", "topic": "Gram Panchayat Services, Streetlights, Drinking Water & Roads", "periods": 7, "seq": 5},
            {"unit": "Safety", "chapter": "Safety and First Aid", "topic": "Traffic Rules, Fire Safety, First Aid Box & Emergency Numbers", "periods": 6, "seq": 6},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_ENG_5",
        "subject_name": "English Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Vocabulary", "chapter": "Fun with Words", "topic": "Rhyming Words, Simple Opposites, Naming Words & Action Words", "periods": 7, "seq": 1},
            {"unit": "Stories", "chapter": "Story Time and Fairy Tales", "topic": "Fables, Panchatantra Tales, Moral Stories & Reading Loud", "periods": 7, "seq": 2},
            {"unit": "Poetry", "chapter": "Poems on Nature", "topic": "Rain, Rainbows, Morning Sun & Recitation with Rhythm", "periods": 6, "seq": 3},
            {"unit": "Communication", "chapter": "Everyday Conversations", "topic": "Greetings, Asking for Help, School Etiquette & Dialogues", "periods": 7, "seq": 4},
            {"unit": "Grammar Basics", "chapter": "Grammar Basics", "topic": "Nouns, Singular/Plural, Pronouns, Simple Present Tense & Sentences", "periods": 8, "seq": 5},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_TEL_5",
        "subject_name": "Telugu Regional Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Badi", "chapter": "Badi Bata", "topic": "Badi Patasala, Chaduvu Viluva, Mitrula Sandadi", "periods": 7, "seq": 1},
            {"unit": "Vennela", "chapter": "Vennela", "topic": "Prakriti Geyam, Vennela Velugulo Patalu", "periods": 6, "seq": 2},
            {"unit": "Neethi", "chapter": "Neethi Kathalu", "topic": "Telangana Neethi Kathalu, Nijayithi & Dharmam", "periods": 7, "seq": 3},
            {"unit": "Pandugalu", "chapter": "Telangana Pandugalu", "topic": "Bathukamma, Bonalu, Sankranti, Ramzan, Christmas Samburalu", "periods": 7, "seq": 4},
            {"unit": "Aksharamala", "chapter": "Varnamala mariyu Guninthalu", "topic": "Achulu, Hallulu, Guninthalu, Sarala Padalu, Vakyalu", "periods": 8, "seq": 5},
        ]
    },
    {
        "board": "STATE",
        "state": "Telangana",
        "class_level": 5,
        "class_name": "Class 5",
        "subject_code": "TS_HIN_5",
        "subject_name": "Hindi Second Language",
        "academic_year_code": "2026-2027",
        "source": "SCERT Telangana State Board Official Curriculum",
        "source_version": "2026.1",
        "items": [
            {"unit": "Prarthana", "chapter": "Prarthana", "topic": "Ishwar Ki Vandana, Satya Aur Ahimsa Ka Marg", "periods": 6, "seq": 1},
            {"unit": "Khel", "chapter": "Khel Kud", "topic": "Khelon Ka Anand, Sharirik Swasthya Aur Sahayog", "periods": 7, "seq": 2},
            {"unit": "Prakriti", "chapter": "Ped Lagao", "topic": "Vriksharopan Ka Mahatva, Hariyali Aur Paryavaran", "periods": 7, "seq": 3},
            {"unit": "Desh Prem", "chapter": "Hamara Desh", "topic": "Rashtriya Dhwaj, Tiranga, Ekata Mein Anekta", "periods": 7, "seq": 4},
            {"unit": "Mahan Vyakti", "chapter": "Chacha Nehru", "topic": "Pandit Jawaharlal Nehru Ka Jeevan, Bal Diwas Ka Mahatva", "periods": 7, "seq": 5},
        ]
    },
    {
        "board": "STATE",
        "state": "Karnataka",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "KT_KAN_8",
        "subject_name": "Kannada",
        "academic_year_code": "2026-2027",
        "source": "DSERT Karnataka State Board Official Curriculum (ktbs.kar.nic.in)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Sahitya", "chapter": "Kannada Sahitya Saurabha", "topic": "Prachina Sahitya, Vachana Sahitya & Dasara Padagalu", "periods": 8, "seq": 1},
            {"unit": "Gadya", "chapter": "Gadya Bhaga", "topic": "Prakruthi, Samaja Mukhi Chinthanegalu & Beladingalu", "periods": 8, "seq": 2},
            {"unit": "Padya", "chapter": "Padya Bhaga", "topic": "Kavya Rachane, Bhasha Soudha & Naitika Moulyagalu", "periods": 8, "seq": 3},
            {"unit": "Vyakarna", "chapter": "Vyakarna Mathu Bhashe", "topic": "Sandhigalu, Samasagalu, Vibhakti Pratyayagalu", "periods": 8, "seq": 4},
        ]
    },
    {
        "board": "STATE",
        "state": "Maharashtra",
        "class_level": 8,
        "class_name": "Class 8",
        "subject_code": "MH_MAR_8",
        "subject_name": "Marathi",
        "academic_year_code": "2026-2027",
        "source": "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
        "source_version": "2026.1",
        "items": [
            {"unit": "Gadhya", "chapter": "Gadhya Vibhag", "topic": "Vividh Nibandh, Kathaa ani Samaj Prabodhan", "periods": 8, "seq": 1},
            {"unit": "Padhya", "chapter": "Padhya Vibhag", "topic": "Sant Sahitya, Abhang, Bhavgeet ani Deshbhakti Geet", "periods": 8, "seq": 2},
            {"unit": "Vyakaran", "chapter": "Vyakaran ani Lekhan", "topic": "Vakya Vichar, Samas, Alankar ani Nibandh Lekhan", "periods": 8, "seq": 3},
        ]
    }
]
