"""implement_student_migration_staging

Revision ID: 051ad7160fe9
Revises: 68b2889a3da3
Create Date: 2026-08-12 13:22:40.929502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '051ad7160fe9'
down_revision: Union[str, None] = '68b2889a3da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_import_rows',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('emis_number', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('medical_information', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_error_code', sa.String(length=100), nullable=True),
    sa.Column('validation_error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_student_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_import_rows_academic_year_id'), 'student_import_rows', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_class_id'), 'student_import_rows', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_created_student_id'), 'student_import_rows', ['created_student_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_id'), 'student_import_rows', ['id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_import_job_id'), 'student_import_rows', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_school_id'), 'student_import_rows', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_section_id'), 'student_import_rows', ['section_id'], unique=False)
    op.create_index(op.f('ix_student_import_rows_tenant_id'), 'student_import_rows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_import_rows_tenant_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_section_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_school_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_import_job_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_created_student_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_class_id'), table_name='student_import_rows')
    op.drop_index(op.f('ix_student_import_rows_academic_year_id'), table_name='student_import_rows')
    op.drop_table('student_import_rows')
    # ### end Alembic commands ###
