"""create_academic_setup_import_rows

Revision ID: 081ecdf144b6
Revises: 051ad7160fe9
Create Date: 2026-08-13 11:52:20.081437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '081ecdf144b6'
down_revision: Union[str, None] = '051ad7160fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_setup_import_rows',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('academic_year_name', sa.String(length=100), nullable=False),
    sa.Column('academic_year_code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('class_code', sa.String(length=50), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('class_category', sa.String(length=50), nullable=False),
    sa.Column('class_capacity', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('section_capacity', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_error_code', sa.String(length=100), nullable=True),
    sa.Column('validation_error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('created_class_id', sa.Uuid(), nullable=True),
    sa.Column('created_section_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_setup_import_rows_academic_year_id'), 'academic_setup_import_rows', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_class_id'), 'academic_setup_import_rows', ['class_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_created_academic_year_id'), 'academic_setup_import_rows', ['created_academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_created_class_id'), 'academic_setup_import_rows', ['created_class_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_created_section_id'), 'academic_setup_import_rows', ['created_section_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_id'), 'academic_setup_import_rows', ['id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_import_job_id'), 'academic_setup_import_rows', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_school_id'), 'academic_setup_import_rows', ['school_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_section_id'), 'academic_setup_import_rows', ['section_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_tenant_id'), 'academic_setup_import_rows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_academic_setup_import_rows_validation_status'), 'academic_setup_import_rows', ['validation_status'], unique=False)
    op.create_index('ix_academic_setup_rows_job_id_row_num', 'academic_setup_import_rows', ['import_job_id', 'row_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_setup_rows_job_id_row_num', table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_validation_status'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_tenant_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_section_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_school_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_import_job_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_created_section_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_created_class_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_created_academic_year_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_class_id'), table_name='academic_setup_import_rows')
    op.drop_index(op.f('ix_academic_setup_import_rows_academic_year_id'), table_name='academic_setup_import_rows')
    op.drop_table('academic_setup_import_rows')
    # ### end Alembic commands ###
