"""implement examination module

Revision ID: 16220cd8ca4a
Revises: e2227f71934f
Create Date: 2026-08-02 11:27:05.467717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16220cd8ca4a'
down_revision: Union[str, None] = 'e2227f71934f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_templates',
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('exam_type', sa.Enum('UNIT_TEST', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'PRE_FINAL', 'ANNUAL', 'SUPPLEMENTARY', name='examtype'), nullable=False),
    sa.Column('subject_configs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_templates_academic_year_id'), 'exam_templates', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_exam_templates_id'), 'exam_templates', ['id'], unique=False)
    op.create_index(op.f('ix_exam_templates_school_id'), 'exam_templates', ['school_id'], unique=False)
    op.create_index(op.f('ix_exam_templates_tenant_id'), 'exam_templates', ['tenant_id'], unique=False)
    op.create_table('examinations',
    sa.Column('exam_name', sa.String(length=200), nullable=False),
    sa.Column('exam_type', sa.Enum('UNIT_TEST', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'PRE_FINAL', 'ANNUAL', 'SUPPLEMENTARY', name='examtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'LOCKED', 'COMPLETED', 'ARCHIVED', name='examstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examinations_academic_year_id'), 'examinations', ['academic_year_id'], unique=False)
    op.create_index('ix_examinations_end_date', 'examinations', ['end_date'], unique=False)
    op.create_index(op.f('ix_examinations_id'), 'examinations', ['id'], unique=False)
    op.create_index(op.f('ix_examinations_school_id'), 'examinations', ['school_id'], unique=False)
    op.create_index('ix_examinations_start_date', 'examinations', ['start_date'], unique=False)
    op.create_index('ix_examinations_status', 'examinations', ['status'], unique=False)
    op.create_index(op.f('ix_examinations_tenant_id'), 'examinations', ['tenant_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('pass_marks', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_subject_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_assignment_id'], ['teacher_subject_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'teacher_subject_assignment_id', name='uq_exam_schedules_tsa_slot')
    )
    op.create_index(op.f('ix_exam_schedules_academic_year_id'), 'exam_schedules', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_class_id'), 'exam_schedules', ['class_id'], unique=False)
    op.create_index('ix_exam_schedules_exam_date', 'exam_schedules', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exam_schedules_exam_id'), 'exam_schedules', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_id'), 'exam_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_school_id'), 'exam_schedules', ['school_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_section_id'), 'exam_schedules', ['section_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_subject_id'), 'exam_schedules', ['subject_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_teacher_subject_assignment_id'), 'exam_schedules', ['teacher_subject_assignment_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_tenant_id'), 'exam_schedules', ['tenant_id'], unique=False)

    # Bulk seed default examination permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Examination", "code": "exam.create", "description": "Allows creating examinations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Examination", "code": "exam.read", "description": "Allows viewing examinations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Examination", "code": "exam.update", "description": "Allows updating examinations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Examination", "code": "exam.delete", "description": "Allows deleting examinations", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_schedules_tenant_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_teacher_subject_assignment_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_subject_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_section_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_school_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_exam_id'), table_name='exam_schedules')
    op.drop_index('ix_exam_schedules_exam_date', table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_class_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_academic_year_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_examinations_tenant_id'), table_name='examinations')
    op.drop_index('ix_examinations_status', table_name='examinations')
    op.drop_index('ix_examinations_start_date', table_name='examinations')
    op.drop_index(op.f('ix_examinations_school_id'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_id'), table_name='examinations')
    op.drop_index('ix_examinations_end_date', table_name='examinations')
    op.drop_index(op.f('ix_examinations_academic_year_id'), table_name='examinations')
    op.drop_table('examinations')
    op.drop_index(op.f('ix_exam_templates_tenant_id'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_school_id'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_id'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_academic_year_id'), table_name='exam_templates')
    op.drop_table('exam_templates')
    
    # Clean up permissions
    op.execute("DELETE FROM permissions WHERE code LIKE 'exam.%';")
    
    # Drop enum types manually
    e_type = sa.Enum('UNIT_TEST', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'PRE_FINAL', 'ANNUAL', 'SUPPLEMENTARY', name='examtype')
    e_type.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('DRAFT', 'PUBLISHED', 'LOCKED', 'COMPLETED', 'ARCHIVED', name='examstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
