"""implement_timetable_module

Revision ID: 180294bda77e
Revises: e10dec6a4888
Create Date: 2026-08-01 14:28:10.879966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '180294bda77e'
down_revision: Union[str, None] = 'e10dec6a4888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('period_type', sa.Enum('REGULAR', 'LAB', 'SPORTS', 'LIBRARY', 'BREAK', 'EXAM', name='periodtype'), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='timetablestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_subject_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_assignment_id'], ['teacher_subject_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'section_id', 'day_of_week', 'period_number', 'academic_year_id', name='uq_timetables_class_slot'),
    sa.UniqueConstraint('teacher_id', 'day_of_week', 'period_number', 'academic_year_id', name='uq_timetables_teacher_slot'),
    sa.UniqueConstraint('teacher_subject_assignment_id', 'day_of_week', 'period_number', name='uq_timetables_tsa_slot')
    )
    op.create_index(op.f('ix_timetables_academic_year_id'), 'timetables', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_timetables_class_id'), 'timetables', ['class_id'], unique=False)
    op.create_index('ix_timetables_day_of_week', 'timetables', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index('ix_timetables_period_number', 'timetables', ['period_number'], unique=False)
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetables_section_id'), 'timetables', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetables_subject_id'), 'timetables', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetables_teacher_id'), 'timetables', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_timetables_teacher_subject_assignment_id'), 'timetables', ['teacher_subject_assignment_id'], unique=False)
    op.create_index(op.f('ix_timetables_tenant_id'), 'timetables', ['tenant_id'], unique=False)

    # Bulk seed default timetable permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Timetable", "code": "timetable.create", "description": "Add school timetable periods", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Timetable", "code": "timetable.read", "description": "View school schedules and timetables", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Timetable", "code": "timetable.update", "description": "Modify school schedules and timetables", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Timetable", "code": "timetable.delete", "description": "Soft delete timetable configurations", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetables_tenant_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_teacher_subject_assignment_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_teacher_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_subject_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_section_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_index('ix_timetables_period_number', table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_index('ix_timetables_day_of_week', table_name='timetables')
    op.drop_index(op.f('ix_timetables_class_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_academic_year_id'), table_name='timetables')
    op.drop_table('timetables')
    
    # Drop enum types manually
    e_day = sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek')
    e_day.drop(op.get_bind(), checkfirst=True)
    
    e_type = sa.Enum('REGULAR', 'LAB', 'SPORTS', 'LIBRARY', 'BREAK', 'EXAM', name='periodtype')
    e_type.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='timetablestatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
