"""implement report card module

Revision ID: 1f1c5c19e22d
Revises: a00b44be5e18
Create Date: 2026-08-02 13:38:17.418737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f1c5c19e22d'
down_revision: Union[str, None] = 'a00b44be5e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_card_publications',
    sa.Column('verification_uuid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'LOCKED', 'ARCHIVED', name='reportcardstatus'), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('pdf_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_report_card_student_year'),
    sa.UniqueConstraint('verification_uuid')
    )
    op.create_index(op.f('ix_report_card_publications_academic_year_id'), 'report_card_publications', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_report_card_publications_id'), 'report_card_publications', ['id'], unique=False)
    op.create_index(op.f('ix_report_card_publications_school_id'), 'report_card_publications', ['school_id'], unique=False)
    op.create_index(op.f('ix_report_card_publications_student_id'), 'report_card_publications', ['student_id'], unique=False)
    op.create_index(op.f('ix_report_card_publications_tenant_id'), 'report_card_publications', ['tenant_id'], unique=False)
    op.create_index('ix_report_card_status', 'report_card_publications', ['status'], unique=False)
    
    # Bulk seed default report card permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Generate Report Card", "code": "report_card.generate", "description": "Allows generating report cards", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Report Card", "code": "report_card.read", "description": "Allows viewing report cards", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Publish Report Card", "code": "report_card.publish", "description": "Allows publishing report cards", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Download Report Card", "code": "report_card.download", "description": "Allows downloading report cards", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_card_status', table_name='report_card_publications')
    op.drop_index(op.f('ix_report_card_publications_tenant_id'), table_name='report_card_publications')
    op.drop_index(op.f('ix_report_card_publications_student_id'), table_name='report_card_publications')
    op.drop_index(op.f('ix_report_card_publications_school_id'), table_name='report_card_publications')
    op.drop_index(op.f('ix_report_card_publications_id'), table_name='report_card_publications')
    op.drop_index(op.f('ix_report_card_publications_academic_year_id'), table_name='report_card_publications')
    op.drop_table('report_card_publications')
    
    # Clean up permissions
    op.execute("DELETE FROM permissions WHERE code LIKE 'report_card.%';")
    
    # Drop enum type manually
    e_status = sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'LOCKED', 'ARCHIVED', name='reportcardstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
