"""implement_academic_year_module

Revision ID: 215993483845
Revises: 6f6a05d124bb
Create Date: 2026-07-31 14:22:53.318849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215993483845'
down_revision: Union[str, None] = '6f6a05d124bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='academicyearstatus'), server_default='UPCOMING', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_academic_years_school_code'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_years_school_name')
    )
    op.create_index('ix_academic_years_dates', 'academic_years', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=False)
    op.create_index('ix_academic_years_is_current', 'academic_years', ['is_current'], unique=False)
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_index('ix_academic_years_status', 'academic_years', ['status'], unique=False)
    op.create_index(op.f('ix_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False)
    
    # Partial unique indexes for school active/current limit checks
    op.create_index(
        'uq_active_academic_year_per_school',
        'academic_years',
        ['school_id'],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL")
    )
    op.create_index(
        'uq_current_academic_year_per_school',
        'academic_years',
        ['school_id'],
        unique=True,
        postgresql_where=sa.text("is_current = true AND deleted_at IS NULL")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_academic_year_per_school', table_name='academic_years')
    op.drop_index('uq_active_academic_year_per_school', table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_tenant_id'), table_name='academic_years')
    op.drop_index('ix_academic_years_status', table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_index('ix_academic_years_is_current', table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_index('ix_academic_years_dates', table_name='academic_years')
    op.drop_table('academic_years')
    
    # Drop enum type in Postgres
    status_enum = sa.Enum('UPCOMING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='academicyearstatus')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
