"""add_multi_channel_notifications

Revision ID: 2454a40d0d69
Revises: 3b29aeac0383
Create Date: 2026-08-21 08:59:20.569576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '2454a40d0d69'
down_revision: Union[str, None] = '3b29aeac0383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'PUSH', 'WHATSAPP', 'SMS', 'EMAIL', name='notificationdeliverychannel'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'CANCELLED', name='notificationdeliverystatus'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_channel'), 'notification_deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_id'), 'notification_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_provider_message_id'), 'notification_deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_recipient_id'), 'notification_deliveries', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_communication_attachments_school_id'), 'communication_attachments', ['school_id'], unique=False)
    op.create_index(op.f('ix_communication_attachments_tenant_id'), 'communication_attachments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_school_id'), 'communication_audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_communication_audit_logs_tenant_id'), 'communication_audit_logs', ['tenant_id'], unique=False)
    op.add_column('notification_preferences', sa.Column('enable_whatsapp', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('notification_preferences', sa.Column('enable_in_app', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('sender_id', sa.Uuid(), nullable=True))
    op.add_column('notifications', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('idempotency_key', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_idempotency_key'), 'notifications', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_unique_constraint('uq_notifications_tenant_idempotency_key', 'notifications', ['tenant_id', 'idempotency_key'])
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_staff_attendances_attendance_date'), table_name='staff_attendances')
    op.create_index('ix_staff_attendance_date', 'staff_attendances', ['attendance_date'], unique=False)
    op.drop_constraint(op.f('staff_attendances_tenant_id_fkey'), 'staff_attendances', type_='foreignkey')
    op.drop_constraint(op.f('teacher_leaves_tenant_id_fkey'), 'teacher_leaves', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('teacher_leaves_tenant_id_fkey'), 'teacher_leaves', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('staff_attendances_tenant_id_fkey'), 'staff_attendances', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_staff_attendance_date', table_name='staff_attendances')
    op.create_index(op.f('ix_staff_attendances_attendance_date'), 'staff_attendances', ['attendance_date'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint('uq_notifications_tenant_idempotency_key', 'notifications', type_='unique')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_idempotency_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_column('notifications', 'idempotency_key')
    op.drop_column('notifications', 'event_type')
    op.drop_column('notifications', 'sender_id')
    op.drop_column('notifications', 'published_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notification_preferences', 'enable_in_app')
    op.drop_column('notification_preferences', 'enable_whatsapp')
    op.drop_index(op.f('ix_communication_audit_logs_tenant_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_audit_logs_school_id'), table_name='communication_audit_logs')
    op.drop_index(op.f('ix_communication_attachments_tenant_id'), table_name='communication_attachments')
    op.drop_index(op.f('ix_communication_attachments_school_id'), table_name='communication_attachments')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_recipient_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_provider_message_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_channel'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
