"""implement notification module

Revision ID: 36ec2ed78a9e
Revises: d91dac4240fd
Create Date: 2026-08-02 16:38:07.906438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ec2ed78a9e'
down_revision: Union[str, None] = 'd91dac4240fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('enable_homework', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_attendance', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_marks', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_report_card', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_announcements', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_events', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_fee', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_push', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_email', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enable_sms', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('ATTENDANCE', 'HOMEWORK', 'EXAMINATION', 'MARKS', 'REPORT_CARD', 'ANNOUNCEMENT', 'EVENT', 'HOLIDAY', 'FEE', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('target_role', sa.Enum('PARENT', 'TEACHER', 'PRINCIPAL', 'ADMIN', 'STAFF', name='notificationtargetrole'), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('related_module', sa.String(length=100), nullable=True),
    sa.Column('related_record_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), nullable=False),
    sa.Column('is_push_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_sms_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_user_id'), 'notifications', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    
    # Seed default notification permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Notification", "code": "notification.create", "description": "Allows creating notification records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Notification", "code": "notification.read", "description": "Allows viewing notification records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Notification", "code": "notification.update", "description": "Allows updating notification records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Notification", "code": "notification.delete", "description": "Allows deleting notification records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Mark Read Notification", "code": "notification.mark_read", "description": "Allows marking notification as read", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM permissions WHERE code IN ('notification.create', 'notification.read', 'notification.update', 'notification.delete', 'notification.mark_read');")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_school_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###

    # Drop enum types in PostgreSQL to clean up fully on downgrade
    op.execute("DROP TYPE IF EXISTS notificationtype;")
    op.execute("DROP TYPE IF EXISTS notificationpriority;")
    op.execute("DROP TYPE IF EXISTS notificationstatus;")
    op.execute("DROP TYPE IF EXISTS notificationtargetrole;")
