"""implement_class_module

Revision ID: 3abe21e1a523
Revises: a63d1ab87bf1
Create Date: 2026-07-31 22:31:37.211081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3abe21e1a523'
down_revision: Union[str, None] = 'a63d1ab87bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PRE_PRIMARY', 'PRIMARY', 'MIDDLE', 'HIGH', 'HIGHER_SECONDARY', 'OTHER', name='classcategory'), nullable=False),
    sa.Column('stream', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('promotion_order', sa.Integer(), nullable=True),
    sa.Column('next_class_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='classstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'code', name='uq_classes_academic_year_code'),
    sa.UniqueConstraint('academic_year_id', 'name', name='uq_classes_academic_year_name')
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_index(op.f('ix_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    
    # Bulk seed default class permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Class", "code": "class.create", "description": "Create school classes", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Class", "code": "class.read", "description": "View school classes", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Class", "code": "class.update", "description": "Modify class configurations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Class", "code": "class.delete", "description": "Soft delete class records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Archive Class", "code": "class.archive", "description": "Archive class configurations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Promote Class", "code": "class.promote", "description": "Configure or run class promotion sequence", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_tenant_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    
    # Drop enum types manually
    class_status = sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='classstatus')
    class_status.drop(op.get_bind(), checkfirst=True)
    
    class_category = sa.Enum('PRE_PRIMARY', 'PRIMARY', 'MIDDLE', 'HIGH', 'HIGHER_SECONDARY', 'OTHER', name='classcategory')
    class_category.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
