"""implement_subject_module

Revision ID: 3d2cf6d3430c
Revises: d0cc7585380f
Create Date: 2026-08-01 12:40:30.639669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d2cf6d3430c'
down_revision: Union[str, None] = 'd0cc7585380f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=150), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('CORE', 'ELECTIVE', 'LANGUAGE', 'OPTIONAL', 'LAB', 'SPORTS', 'ARTS', 'CO_CURRICULAR', name='subjectcategory'), nullable=False),
    sa.Column('subject_type', sa.Enum('THEORY', 'PRACTICAL', 'THEORY_PRACTICAL', name='subjecttype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('credit_hours', sa.Integer(), nullable=True),
    sa.Column('weekly_periods', sa.Integer(), nullable=True),
    sa.Column('theory_marks', sa.Integer(), nullable=True),
    sa.Column('practical_marks', sa.Integer(), nullable=True),
    sa.Column('pass_marks', sa.Integer(), nullable=True),
    sa.Column('display_color', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='subjectstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'subject_code', name='uq_subjects_code_ay'),
    sa.UniqueConstraint('academic_year_id', 'subject_name', name='uq_subjects_name_ay')
    )
    op.create_index(op.f('ix_subjects_academic_year_id'), 'subjects', ['academic_year_id'], unique=False)
    op.create_index('ix_subjects_category', 'subjects', ['category'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_index('ix_subjects_status', 'subjects', ['status'], unique=False)
    op.create_index('ix_subjects_subject_code', 'subjects', ['subject_code'], unique=False)
    op.create_index('ix_subjects_subject_name', 'subjects', ['subject_name'], unique=False)
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)

    # Bulk seed default subject permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Subject", "code": "subject.create", "description": "Add school academic subject", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Subject", "code": "subject.read", "description": "View school academic subjects catalog", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Subject", "code": "subject.update", "description": "Modify academic subject properties", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Subject", "code": "subject.delete", "description": "Soft delete academic subject records", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_index('ix_subjects_subject_name', table_name='subjects')
    op.drop_index('ix_subjects_subject_code', table_name='subjects')
    op.drop_index('ix_subjects_status', table_name='subjects')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index('ix_subjects_category', table_name='subjects')
    op.drop_index(op.f('ix_subjects_academic_year_id'), table_name='subjects')
    op.drop_table('subjects')
    
    # Drop enum types manually
    e_status = sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='subjectstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    
    e_cat = sa.Enum('CORE', 'ELECTIVE', 'LANGUAGE', 'OPTIONAL', 'LAB', 'SPORTS', 'ARTS', 'CO_CURRICULAR', name='subjectcategory')
    e_cat.drop(op.get_bind(), checkfirst=True)
    
    e_type = sa.Enum('THEORY', 'PRACTICAL', 'THEORY_PRACTICAL', name='subjecttype')
    e_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
