"""implement_section_module

Revision ID: 507df354b420
Revises: 3abe21e1a523
Create Date: 2026-08-01 09:28:30.717216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '507df354b420'
down_revision: Union[str, None] = '3abe21e1a523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='sectionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'code', name='uq_sections_class_code'),
    sa.UniqueConstraint('class_id', 'name', name='uq_sections_class_name')
    )
    op.create_index(op.f('ix_sections_academic_year_id'), 'sections', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_school_id'), 'sections', ['school_id'], unique=False)
    op.create_index(op.f('ix_sections_tenant_id'), 'sections', ['tenant_id'], unique=False)
    
    # Bulk seed default section permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Section", "code": "section.create", "description": "Create school sections", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Section", "code": "section.read", "description": "View school sections", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Section", "code": "section.update", "description": "Modify section configurations", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Section", "code": "section.delete", "description": "Soft delete section records", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_tenant_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_school_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_academic_year_id'), table_name='sections')
    op.drop_table('sections')
    
    # Drop enum types manually
    section_status = sa.Enum('ACTIVE', 'INACTIVE', name='sectionstatus')
    section_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
