"""implement syllabus module

Revision ID: 54f702b52146
Revises: 52b4a3df0926
Create Date: 2026-08-16 12:49:47.384701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '54f702b52146'
down_revision: Union[str, None] = '52b4a3df0926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabuses',
    sa.Column('syllabus_code', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=150), nullable=False),
    sa.Column('chapter_name', sa.String(length=150), nullable=False),
    sa.Column('topic_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'class_id', 'subject_id', 'syllabus_code', name='uq_syllabus_code_ay_class_sub')
    )
    op.create_index(op.f('ix_syllabuses_academic_year_id'), 'syllabuses', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_syllabuses_class_id'), 'syllabuses', ['class_id'], unique=False)
    op.create_index(op.f('ix_syllabuses_id'), 'syllabuses', ['id'], unique=False)
    op.create_index(op.f('ix_syllabuses_school_id'), 'syllabuses', ['school_id'], unique=False)
    op.create_index(op.f('ix_syllabuses_subject_id'), 'syllabuses', ['subject_id'], unique=False)
    op.create_index('ix_syllabuses_syllabus_code', 'syllabuses', ['syllabus_code'], unique=False)
    op.create_index(op.f('ix_syllabuses_tenant_id'), 'syllabuses', ['tenant_id'], unique=False)
    
    # Seed default syllabus permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Syllabus", "code": "syllabus.create", "description": "Allows creating syllabus records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Syllabus", "code": "syllabus.read", "description": "Allows viewing syllabus records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Syllabus", "code": "syllabus.update", "description": "Allows updating syllabus records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Syllabus", "code": "syllabus.delete", "description": "Allows deleting syllabus records", "created_at": now, "updated_at": now},
    ]
    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabuses_tenant_id'), table_name='syllabuses')
    op.drop_index('ix_syllabuses_syllabus_code', table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_subject_id'), table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_school_id'), table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_id'), table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_class_id'), table_name='syllabuses')
    op.drop_index(op.f('ix_syllabuses_academic_year_id'), table_name='syllabuses')
    op.drop_table('syllabuses')
    
    # Clean up permissions
    op.execute("DELETE FROM permissions WHERE code LIKE 'syllabus.%';")
    # ### end Alembic commands ###
