"""create student_guardian_import_rows

Revision ID: 5b8bff5f3ef6
Revises: 9300d1926387
Create Date: 2026-08-13 15:58:21.671591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '5b8bff5f3ef6'
down_revision: Union[str, None] = '9300d1926387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_guardian_import_rows',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('student_admission_number', sa.String(length=255), nullable=False),
    sa.Column('guardian_id', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('can_pickup_student', sa.Boolean(), nullable=True),
    sa.Column('receives_notifications', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_error_code', sa.String(length=100), nullable=True),
    sa.Column('validation_error_message', sa.String(length=1000), nullable=True),
    sa.Column('resolved_student_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_guardian_id', sa.Uuid(), nullable=True),
    sa.Column('created_mapping_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_mapping_id'], ['student_guardians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_guardian_id'], ['guardians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardian_import_rows_created_mapping_id'), 'student_guardian_import_rows', ['created_mapping_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_guardian_id'), 'student_guardian_import_rows', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_id'), 'student_guardian_import_rows', ['id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_import_job_id'), 'student_guardian_import_rows', ['import_job_id'], unique=False)
    op.create_index('ix_student_guardian_import_rows_job_id_row_num', 'student_guardian_import_rows', ['import_job_id', 'row_number'], unique=True)
    op.create_index(op.f('ix_student_guardian_import_rows_resolved_guardian_id'), 'student_guardian_import_rows', ['resolved_guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_resolved_student_id'), 'student_guardian_import_rows', ['resolved_student_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_school_id'), 'student_guardian_import_rows', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_student_admission_number'), 'student_guardian_import_rows', ['student_admission_number'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_tenant_id'), 'student_guardian_import_rows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_import_rows_validation_status'), 'student_guardian_import_rows', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_guardian_import_rows_validation_status'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_tenant_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_student_admission_number'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_school_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_resolved_student_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_resolved_guardian_id'), table_name='student_guardian_import_rows')
    op.drop_index('ix_student_guardian_import_rows_job_id_row_num', table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_import_job_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_guardian_id'), table_name='student_guardian_import_rows')
    op.drop_index(op.f('ix_student_guardian_import_rows_created_mapping_id'), table_name='student_guardian_import_rows')
    op.drop_table('student_guardian_import_rows')
    # ### end Alembic commands ###
