"""add_indian_school_fields

Revision ID: 634653e1f2d8
Revises: 4619391bf019
Create Date: 2026-07-29 16:26:07.642565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634653e1f2d8'
down_revision: Union[str, None] = '4619391bf019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('udise_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_schools_udise_code'), 'schools', ['udise_code'], unique=True)
    op.add_column('tenants', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('gstin', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'gstin')
    op.drop_column('tenants', 'pan')
    op.drop_index(op.f('ix_schools_udise_code'), table_name='schools')
    op.drop_column('schools', 'udise_code')
    # ### end Alembic commands ###
