"""implement_migration_foundation

Revision ID: 68b2889a3da3
Revises: 322808ea39d1
Create Date: 2026-08-12 08:52:53.560681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '68b2889a3da3'
down_revision: Union[str, None] = '322808ea39d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('import_type', sa.Enum('STUDENTS', 'ACADEMIC_SETUP', 'GUARDIANS', 'GUARDIAN_MAPPING', 'STAFF', 'FEE_MASTERS', 'FEE_ASSIGNMENTS', 'PAYMENTS', 'OPENING_BALANCES', 'DOCUMENTS', name='importtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'VALIDATED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED', name='importjobstatus'), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.String(length=1000), nullable=True),
    sa.Column('job_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_checksum_active', 'import_jobs', ['tenant_id', 'school_id', 'import_type', 'file_checksum'], unique=False, postgresql_where=sa.text("status IN ('VALIDATING', 'VALIDATED', 'RUNNING')"))
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_import_jobs_school_id'), 'import_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_tenant_id'), 'import_jobs', ['tenant_id'], unique=False)
    op.create_table('import_job_rows',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('row_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_job_rows_id'), 'import_job_rows', ['id'], unique=False)
    op.create_index(op.f('ix_import_job_rows_import_job_id'), 'import_job_rows', ['import_job_id'], unique=False)
    op.create_index('ix_import_job_rows_job_id_row_num', 'import_job_rows', ['import_job_id', 'row_number'], unique=True)
    
    # --- Custom Permission Seeds ---
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Read Migration Job", "code": "migration.read", "description": "Allows viewing migration jobs and reports", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Create Migration Job", "code": "migration.create", "description": "Allows creating migration jobs", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Execute Migration Job", "code": "migration.execute", "description": "Allows executing migration jobs", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Cancel Migration Job", "code": "migration.cancel", "description": "Allows canceling migration jobs", "created_at": now, "updated_at": now},
    ]

    bind = op.get_bind()
    for p in permissions_data:
        exist_p = bind.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": p["code"]}).fetchone()
        if not exist_p:
            bind.execute(
                sa.text(
                    "INSERT INTO permissions (id, name, code, description, created_at, updated_at) "
                    "VALUES (:id, :name, :code, :description, :created_at, :updated_at)"
                ),
                p
            )
            
    # Resolve the Principal role across all tenants and map permissions
    roles_res = bind.execute(
        sa.text("SELECT id FROM roles WHERE code = 'PRINCIPAL'")
    ).fetchall()
    
    # Resolve the Staff role across all tenants and map read/create permissions
    staff_roles_res = bind.execute(
        sa.text("SELECT id FROM roles WHERE code = 'STAFF'")
    ).fetchall()
    
    # Map read, create, execute, cancel permissions to Principal
    all_perm_codes = ['migration.read', 'migration.create', 'migration.execute', 'migration.cancel']
    perms_res = bind.execute(
        sa.text("SELECT id, code FROM permissions WHERE code = ANY(:codes)"),
        {"codes": all_perm_codes}
    ).fetchall()
    
    perms = {row[1]: row[0] for row in perms_res}
    
    # PRINCIPAL maps all 4
    for role in roles_res:
        role_id = role[0]
        for code in all_perm_codes:
            perm_id = perms.get(code)
            if perm_id:
                exist_link = bind.execute(
                    sa.text("SELECT 1 FROM role_permissions WHERE role_id = :r_id AND permission_id = :p_id"),
                    {"r_id": role_id, "p_id": perm_id}
                ).fetchone()
                if not exist_link:
                    bind.execute(
                        sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:r_id, :p_id)"),
                        {"r_id": role_id, "p_id": perm_id}
                    )
                    
    # STAFF maps only read and create
    staff_perm_codes = ['migration.read', 'migration.create']
    for role in staff_roles_res:
        role_id = role[0]
        for code in staff_perm_codes:
            perm_id = perms.get(code)
            if perm_id:
                exist_link = bind.execute(
                    sa.text("SELECT 1 FROM role_permissions WHERE role_id = :r_id AND permission_id = :p_id"),
                    {"r_id": role_id, "p_id": perm_id}
                ).fetchone()
                if not exist_link:
                    bind.execute(
                        sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:r_id, :p_id)"),
                        {"r_id": role_id, "p_id": perm_id}
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop table structures
    op.drop_index('ix_import_job_rows_job_id_row_num', table_name='import_job_rows')
    op.drop_index(op.f('ix_import_job_rows_import_job_id'), table_name='import_job_rows')
    op.drop_index(op.f('ix_import_job_rows_id'), table_name='import_job_rows')
    op.drop_table('import_job_rows')
    op.drop_index(op.f('ix_import_jobs_tenant_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_school_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_index('ix_import_jobs_checksum_active', table_name='import_jobs', postgresql_where=sa.text("status IN ('VALIDATING', 'VALIDATED', 'RUNNING')"))
    op.drop_table('import_jobs')
    
    # --- Custom Permission Cleanup ---
    bind = op.get_bind()
    all_perm_codes = ['migration.read', 'migration.create', 'migration.execute', 'migration.cancel']
    
    # Delete associations
    bind.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": all_perm_codes}
    )
    # Delete permissions
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": all_perm_codes}
    )
    # ### end Alembic commands ###
