"""implement user device token and update notification schema

Revision ID: 6c07269ae8b8
Revises: 54f702b52146
Create Date: 2026-08-17 11:56:59.548610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '6c07269ae8b8'
down_revision: Union[str, None] = '54f702b52146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_tokens',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('app_type', sa.String(length=50), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_device_tokens_id'), 'user_device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_device_tokens_tenant_id'), 'user_device_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_device_tokens_user_id'), 'user_device_tokens', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('student_id', sa.Uuid(), nullable=True))
    op.add_column('notifications', sa.Column('event_key', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('push_status', sa.String(length=50), server_default='NOT_CONFIGURED', nullable=False))
    op.add_column('notifications', sa.Column('email_status', sa.String(length=50), server_default='NOT_CONFIGURED', nullable=False))
    op.add_column('notifications', sa.Column('sms_status', sa.String(length=50), server_default='NOT_CONFIGURED', nullable=False))
    op.create_index(op.f('ix_notifications_event_key'), 'notifications', ['event_key'], unique=False)
    op.create_index(op.f('ix_notifications_student_id'), 'notifications', ['student_id'], unique=False)
    op.create_unique_constraint('uq_notifications_tenant_event_key', 'notifications', ['tenant_id', 'event_key'])
    op.create_foreign_key(None, 'notifications', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint('uq_notifications_tenant_event_key', 'notifications', type_='unique')
    op.drop_index(op.f('ix_notifications_student_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_key'), table_name='notifications')
    op.drop_column('notifications', 'sms_status')
    op.drop_column('notifications', 'email_status')
    op.drop_column('notifications', 'push_status')
    op.drop_column('notifications', 'event_key')
    op.drop_column('notifications', 'student_id')
    op.drop_index(op.f('ix_user_device_tokens_user_id'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_tenant_id'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_id'), table_name='user_device_tokens')
    op.drop_table('user_device_tokens')
    # ### end Alembic commands ###
