"""implement_school_module

Revision ID: 6f6a05d124bb
Revises: 634653e1f2d8
Create Date: 2026-07-29 23:43:28.788676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6a05d124bb'
down_revision: Union[str, None] = '634653e1f2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types in Postgres first
    school_board = sa.Enum('CBSE', 'ICSE', 'SSC', 'STATE', 'IB', 'IGCSE', 'CAMBRIDGE', 'OTHER', name='schoolboard')
    school_board.create(op.get_bind(), checkfirst=True)
    
    school_type = sa.Enum('PRIMARY', 'HIGH_SCHOOL', 'JR_COLLEGE', 'DEGREE_COLLEGE', 'UNIVERSITY', 'OTHER', name='schooltype')
    school_type.create(op.get_bind(), checkfirst=True)
    
    school_status = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='schoolstatus')
    school_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('code', sa.String(length=20), nullable=False))
    op.add_column('schools', sa.Column('board', sa.Enum('CBSE', 'ICSE', 'SSC', 'STATE', 'IB', 'IGCSE', 'CAMBRIDGE', 'OTHER', name='schoolboard'), nullable=False))
    op.add_column('schools', sa.Column('school_type', sa.Enum('PRIMARY', 'HIGH_SCHOOL', 'JR_COLLEGE', 'DEGREE_COLLEGE', 'UNIVERSITY', 'OTHER', name='schooltype'), nullable=False))
    op.add_column('schools', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('schools', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('principal_name', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('country', sa.String(length=100), server_default='India', nullable=True))
    op.add_column('schools', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('schools', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('schools', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='schoolstatus'), server_default='ACTIVE', nullable=False))
    op.add_column('schools', sa.Column('settings', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('schools', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index('ix_schools_board', 'schools', ['board'], unique=False)
    op.create_index('ix_schools_city', 'schools', ['city'], unique=False)
    op.create_index('ix_schools_is_active', 'schools', ['is_active'], unique=False)
    op.create_index('ix_schools_status', 'schools', ['status'], unique=False)
    op.create_unique_constraint('uq_schools_tenant_code', 'schools', ['tenant_id', 'code'])
    op.create_unique_constraint('uq_schools_tenant_email', 'schools', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_schools_tenant_email', 'schools', type_='unique')
    op.drop_constraint('uq_schools_tenant_code', 'schools', type_='unique')
    op.drop_index('ix_schools_status', table_name='schools')
    op.drop_index('ix_schools_is_active', table_name='schools')
    op.drop_index('ix_schools_city', table_name='schools')
    op.drop_index('ix_schools_board', table_name='schools')
    op.drop_column('schools', 'version')
    op.drop_column('schools', 'settings')
    op.drop_column('schools', 'status')
    op.drop_column('schools', 'is_active')
    op.drop_column('schools', 'logo_url')
    op.drop_column('schools', 'postal_code')
    op.drop_column('schools', 'country')
    op.drop_column('schools', 'state')
    op.drop_column('schools', 'city')
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'principal_name')
    op.drop_column('schools', 'website')
    op.drop_column('schools', 'phone')
    op.drop_column('schools', 'email')
    op.drop_column('schools', 'school_type')
    op.drop_column('schools', 'board')
    op.drop_column('schools', 'code')
    op.drop_column('schools', 'display_name')
    
    # Drop enum types in Postgres
    school_status = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='schoolstatus')
    school_status.drop(op.get_bind(), checkfirst=True)
    
    school_type = sa.Enum('PRIMARY', 'HIGH_SCHOOL', 'JR_COLLEGE', 'DEGREE_COLLEGE', 'UNIVERSITY', 'OTHER', name='schooltype')
    school_type.drop(op.get_bind(), checkfirst=True)
    
    school_board = sa.Enum('CBSE', 'ICSE', 'SSC', 'STATE', 'IB', 'IGCSE', 'CAMBRIDGE', 'OTHER', name='schoolboard')
    school_board.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
