"""add_login_id_and_parent_sequence

Revision ID: 793f22643c13
Revises: 2454a40d0d69
Create Date: 2026-08-22 16:57:23.810440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '793f22643c13'
down_revision: Union[str, None] = '2454a40d0d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_login_sequences',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('next_sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'school_id', name='uq_parent_login_sequences_tenant_school')
    )
    op.create_index(op.f('ix_parent_login_sequences_id'), 'parent_login_sequences', ['id'], unique=False)
    op.create_index('ix_parent_login_sequences_school_id', 'parent_login_sequences', ['school_id'], unique=False)
    op.create_index(op.f('ix_parent_login_sequences_tenant_id'), 'parent_login_sequences', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('login_id', sa.String(length=50), nullable=True))
    op.create_index('ix_users_login_id', 'users', ['login_id'], unique=False)
    op.create_unique_constraint('uq_users_tenant_login_id', 'users', ['tenant_id', 'login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_login_id', 'users', type_='unique')
    op.drop_index('ix_users_login_id', table_name='users')
    op.drop_column('users', 'login_id')
    op.drop_index(op.f('ix_parent_login_sequences_tenant_id'), table_name='parent_login_sequences')
    op.drop_index('ix_parent_login_sequences_school_id', table_name='parent_login_sequences')
    op.drop_index(op.f('ix_parent_login_sequences_id'), table_name='parent_login_sequences')
    op.drop_table('parent_login_sequences')
    # ### end Alembic commands ###
