"""create_guardian_import_rows

Revision ID: 9300d1926387
Revises: 081ecdf144b6
Create Date: 2026-08-13 15:19:55.152079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Additional imports here if needed

# revision identifiers, used by Alembic.
revision: str = '9300d1926387'
down_revision: Union[str, None] = '081ecdf144b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_import_rows',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('guardian_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('qualification', sa.String(length=150), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_error_code', sa.String(length=100), nullable=True),
    sa.Column('validation_error_message', sa.String(length=1000), nullable=True),
    sa.Column('resolved_guardian_id', sa.Uuid(), nullable=True),
    sa.Column('created_guardian_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_guardian_id'], ['guardians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_guardian_id'], ['guardians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_import_rows_created_guardian_id'), 'guardian_import_rows', ['created_guardian_id'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_id'), 'guardian_import_rows', ['id'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_import_job_id'), 'guardian_import_rows', ['import_job_id'], unique=False)
    op.create_index('ix_guardian_import_rows_job_id_row_num', 'guardian_import_rows', ['import_job_id', 'row_number'], unique=True)
    op.create_index(op.f('ix_guardian_import_rows_resolved_guardian_id'), 'guardian_import_rows', ['resolved_guardian_id'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_school_id'), 'guardian_import_rows', ['school_id'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_source_identifier'), 'guardian_import_rows', ['source_identifier'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_tenant_id'), 'guardian_import_rows', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_guardian_import_rows_validation_status'), 'guardian_import_rows', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardian_import_rows_validation_status'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_tenant_id'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_source_identifier'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_school_id'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_resolved_guardian_id'), table_name='guardian_import_rows')
    op.drop_index('ix_guardian_import_rows_job_id_row_num', table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_import_job_id'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_id'), table_name='guardian_import_rows')
    op.drop_index(op.f('ix_guardian_import_rows_created_guardian_id'), table_name='guardian_import_rows')
    op.drop_table('guardian_import_rows')
    # ### end Alembic commands ###
