"""implement marks module

Revision ID: a00b44be5e18
Revises: 16220cd8ca4a
Create Date: 2026-08-02 12:46:39.279284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a00b44be5e18'
down_revision: Union[str, None] = '16220cd8ca4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('maximum_marks', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result_status', sa.Enum('PRESENT', 'ABSENT', 'MALPRACTICE', 'EXEMPTED', name='examresult'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'LOCKED', name='marksstatus'), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('audit_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('examination_id', sa.Uuid(), nullable=False),
    sa.Column('exam_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_subject_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_assignment_id'], ['teacher_subject_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_schedule_id', 'student_id', name='uq_marks_student_subject_schedule')
    )
    op.create_index(op.f('ix_marks_academic_year_id'), 'marks', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_marks_class_id'), 'marks', ['class_id'], unique=False)
    op.create_index(op.f('ix_marks_exam_schedule_id'), 'marks', ['exam_schedule_id'], unique=False)
    op.create_index(op.f('ix_marks_examination_id'), 'marks', ['examination_id'], unique=False)
    op.create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    op.create_index(op.f('ix_marks_school_id'), 'marks', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_section_id'), 'marks', ['section_id'], unique=False)
    op.create_index('ix_marks_status', 'marks', ['status'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_marks_subject_id'), 'marks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_marks_teacher_id'), 'marks', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_marks_teacher_subject_assignment_id'), 'marks', ['teacher_subject_assignment_id'], unique=False)
    op.create_index(op.f('ix_marks_tenant_id'), 'marks', ['tenant_id'], unique=False)
    
    # Bulk seed default marks permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Marks", "code": "marks.create", "description": "Allows creating marks records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Marks", "code": "marks.read", "description": "Allows viewing marks records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Marks", "code": "marks.update", "description": "Allows updating marks records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Marks", "code": "marks.delete", "description": "Allows deleting marks records", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Publish Marks", "code": "marks.publish", "description": "Allows publishing marks records", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marks_tenant_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_teacher_subject_assignment_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_teacher_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_subject_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index('ix_marks_status', table_name='marks')
    op.drop_index(op.f('ix_marks_section_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_school_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_examination_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_exam_schedule_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_class_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_academic_year_id'), table_name='marks')
    op.drop_table('marks')
    
    # Clean up permissions
    op.execute("DELETE FROM permissions WHERE code LIKE 'marks.%';")
    
    # Drop enum types manually
    e_result = sa.Enum('PRESENT', 'ABSENT', 'MALPRACTICE', 'EXEMPTED', name='examresult')
    e_result.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('DRAFT', 'PUBLISHED', 'LOCKED', name='marksstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
