"""implement academic year module

Revision ID: b22e07413f51
Revises: 215993483845
Create Date: 2026-07-31 16:16:15.721889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e07413f51'
down_revision: Union[str, None] = '215993483845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_active_academic_year_per_school'), table_name='academic_years', postgresql_where="((status = 'ACTIVE'::academicyearstatus) AND (deleted_at IS NULL))")
    op.drop_index(op.f('uq_current_academic_year_per_school'), table_name='academic_years', postgresql_where='((is_current = true) AND (deleted_at IS NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_current_academic_year_per_school'), 'academic_years', ['school_id'], unique=True, postgresql_where='((is_current = true) AND (deleted_at IS NULL))')
    op.create_index(op.f('uq_active_academic_year_per_school'), 'academic_years', ['school_id'], unique=True, postgresql_where="((status = 'ACTIVE'::academicyearstatus) AND (deleted_at IS NULL))")
    # ### end Alembic commands ###
