"""implement_guardian_module

Revision ID: b505052bbb05
Revises: 5899254e74a3
Create Date: 2026-08-01 11:30:28.534274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b505052bbb05'
down_revision: Union[str, None] = '5899254e74a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('guardian_type', sa.Enum('FATHER', 'MOTHER', 'LEGAL_GUARDIAN', 'GRANDPARENT', 'UNCLE', 'AUNT', 'OTHER', name='guardiantype'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='studentgender', create_type=False), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('qualification', sa.String(length=150), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('is_mobile_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('communication_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='guardianstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'aadhaar_number', name='uq_guardians_aadhaar'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_guardians_email'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_guardians_mobile'),
    sa.UniqueConstraint('tenant_id', 'pan_number', name='uq_guardians_pan')
    )
    op.create_index(op.f('ix_guardians_id'), 'guardians', ['id'], unique=False)
    op.create_index(op.f('ix_guardians_school_id'), 'guardians', ['school_id'], unique=False)
    op.create_index(op.f('ix_guardians_tenant_id'), 'guardians', ['tenant_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', 'GRANDPARENT', 'RELATIVE', 'OTHER', name='studentguardianrelationship'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('can_pickup_student', sa.Boolean(), nullable=False),
    sa.Column('receives_notifications', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'guardian_id', name='uq_student_guardians_mapping')
    )
    op.create_index(op.f('ix_student_guardians_guardian_id'), 'student_guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_id'), 'student_guardians', ['id'], unique=False)
    op.create_index(op.f('ix_student_guardians_school_id'), 'student_guardians', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_tenant_id'), 'student_guardians', ['tenant_id'], unique=False)

    # Bulk seed default guardian permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Guardian", "code": "guardian.create", "description": "Add school guardians profile", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Guardian", "code": "guardian.read", "description": "View school guardians profile and list", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Guardian", "code": "guardian.update", "description": "Modify guardian profiles", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Guardian", "code": "guardian.delete", "description": "Soft delete guardian profiles", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_guardians_tenant_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_school_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_guardian_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_guardians_tenant_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_school_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_id'), table_name='guardians')
    op.drop_table('guardians')

    # Drop enum types manually
    g_type = sa.Enum('FATHER', 'MOTHER', 'LEGAL_GUARDIAN', 'GRANDPARENT', 'UNCLE', 'AUNT', 'OTHER', name='guardiantype')
    g_type.drop(op.get_bind(), checkfirst=True)
    
    g_status = sa.Enum('ACTIVE', 'INACTIVE', name='guardianstatus')
    g_status.drop(op.get_bind(), checkfirst=True)
    
    sg_rel = sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', 'GRANDPARENT', 'RELATIVE', 'OTHER', name='studentguardianrelationship')
    sg_rel.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
