"""add_tenant_version_column

Revision ID: be868e9a665e
Revises: bf2f09d4c019
Create Date: 2026-07-29 16:09:24.995450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be868e9a665e'
down_revision: Union[str, None] = 'bf2f09d4c019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'version')
    # ### end Alembic commands ###
