"""update_tenant_and_add_school

Revision ID: bf2f09d4c019
Revises: 7b052063bf02
Create Date: 2026-07-29 15:59:52.297688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2f09d4c019'
down_revision: Union[str, None] = '7b052063bf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type first
    tenant_status = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenantstatus')
    tenant_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_tenant_id'), 'schools', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('settings', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True))
    
    # Cast status column to enum safely by dropping default, altering type, and setting new default
    op.execute("ALTER TABLE tenants ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE tenants ALTER COLUMN status TYPE tenantstatus USING status::tenantstatus")
    op.execute("ALTER TABLE tenants ALTER COLUMN status SET DEFAULT 'ACTIVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tenants ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE tenants ALTER COLUMN status TYPE VARCHAR(20) USING status::VARCHAR")
    op.execute("ALTER TABLE tenants ALTER COLUMN status SET DEFAULT 'ACTIVE'")
    
    op.drop_column('tenants', 'subscription_end')
    op.drop_column('tenants', 'subscription_start')
    op.drop_column('tenants', 'plan')
    op.drop_column('tenants', 'settings')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'display_name')
    op.drop_index(op.f('ix_schools_tenant_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    
    # Drop enum type
    tenant_status = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenantstatus')
    tenant_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
