"""implement_teacher_module

Revision ID: d0cc7585380f
Revises: b505052bbb05
Create Date: 2026-08-01 12:13:57.956822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0cc7585380f'
down_revision: Union[str, None] = 'b505052bbb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('staff_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='studentgender', create_type=False), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('official_email', sa.String(length=255), nullable=False),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('date_of_confirmation', sa.Date(), nullable=True),
    sa.Column('date_of_resignation', sa.Date(), nullable=True),
    sa.Column('date_of_retirement', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employmenttype'), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'RETIRED', name='teacherstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'employee_code', name='uq_teachers_employee_school'),
    sa.UniqueConstraint('school_id', 'staff_code', name='uq_teachers_staff_school'),
    sa.UniqueConstraint('tenant_id', 'aadhaar_number', name='uq_teachers_aadhaar'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_teachers_mobile'),
    sa.UniqueConstraint('tenant_id', 'official_email', name='uq_teachers_official_email'),
    sa.UniqueConstraint('tenant_id', 'pan_number', name='uq_teachers_pan'),
    sa.UniqueConstraint('tenant_id', 'personal_email', name='uq_teachers_personal_email')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_teachers_tenant_id'), 'teachers', ['tenant_id'], unique=False)

    # Bulk seed default teacher permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Teacher", "code": "teacher.create", "description": "Add school teachers profile", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Teacher", "code": "teacher.read", "description": "View school teachers list and details", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Teacher", "code": "teacher.update", "description": "Modify teacher profile properties", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Teacher", "code": "teacher.delete", "description": "Soft delete teacher records", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_tenant_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    
    # Drop enum types manually
    e_type = sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employmenttype')
    e_type.drop(op.get_bind(), checkfirst=True)
    
    t_status = sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'RETIRED', name='teacherstatus')
    t_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
