"""implement_attendance_module

Revision ID: d1351c0630e0
Revises: 180294bda77e
Create Date: 2026-08-01 15:15:44.579706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1351c0630e0'
down_revision: Union[str, None] = '180294bda77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'LOCKED', name='attendancesessionstatus'), nullable=False),
    sa.Column('marked_by', sa.Uuid(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('timetable_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'attendance_date', name='uq_attendance_sessions_slot')
    )
    op.create_index(op.f('ix_attendance_sessions_academic_year_id'), 'attendance_sessions', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_class_id'), 'attendance_sessions', ['class_id'], unique=False)
    op.create_index('ix_attendance_sessions_date', 'attendance_sessions', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_school_id'), 'attendance_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_section_id'), 'attendance_sessions', ['section_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_subject_id'), 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_tenant_id'), 'attendance_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_timetable_id'), 'attendance_sessions', ['timetable_id'], unique=False)
    op.create_table('attendances',
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'MEDICAL_LEAVE', 'EXCUSED', 'HOLIDAY', 'ONLINE', name='attendancestatus'), nullable=False),
    sa.Column('attendance_source', sa.Enum('MANUAL', 'BIOMETRIC', 'RFID', 'FACE_RECOGNITION', 'IMPORT', name='attendancesource'), nullable=False),
    sa.Column('attendance_reason', sa.Enum('SICK', 'PERSONAL', 'SPORTS', 'OFFICIAL', 'UNKNOWN', name='attendancereason'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('parent_viewed', sa.Boolean(), nullable=False),
    sa.Column('parent_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{"notification_status": "PENDING", "notification_sent_at": null, "sms_sent": false, "push_sent": false}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{"attendance_percentage": null, "absence_streak": null, "predicted_dropout_risk": null, "late_frequency": null, "attendance_trend": null, "exam_risk_score": null}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('timetable_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_attendances_session_student'),
    sa.UniqueConstraint('student_id', 'timetable_id', 'attendance_date', name='uq_attendances_student_slot')
    )
    op.create_index(op.f('ix_attendances_academic_year_id'), 'attendances', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_attendances_attendance_session_id'), 'attendances', ['attendance_session_id'], unique=False)
    op.create_index(op.f('ix_attendances_class_id'), 'attendances', ['class_id'], unique=False)
    op.create_index('ix_attendances_date', 'attendances', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_school_id'), 'attendances', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendances_section_id'), 'attendances', ['section_id'], unique=False)
    op.create_index('ix_attendances_status', 'attendances', ['attendance_status'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendances_subject_id'), 'attendances', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendances_teacher_id'), 'attendances', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_attendances_tenant_id'), 'attendances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendances_timetable_id'), 'attendances', ['timetable_id'], unique=False)

    # Bulk seed default attendance permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Student Attendance", "code": "attendance.create", "description": "Mark student period attendance logs", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Student Attendance", "code": "attendance.read", "description": "View student attendance histories", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Student Attendance", "code": "attendance.update", "description": "Modify student attendance marks", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Student Attendance", "code": "attendance.delete", "description": "Soft delete marked student attendances", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_timetable_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_tenant_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_teacher_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_subject_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index('ix_attendances_status', table_name='attendances')
    op.drop_index(op.f('ix_attendances_section_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_school_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index('ix_attendances_date', table_name='attendances')
    op.drop_index(op.f('ix_attendances_class_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_session_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_academic_year_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_attendance_sessions_timetable_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_tenant_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_subject_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_section_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_school_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_date', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_academic_year_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')

    # Drop enum types manually
    e_s_status = sa.Enum('DRAFT', 'SUBMITTED', 'LOCKED', name='attendancesessionstatus')
    e_s_status.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'MEDICAL_LEAVE', 'EXCUSED', 'HOLIDAY', 'ONLINE', name='attendancestatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    
    e_source = sa.Enum('MANUAL', 'BIOMETRIC', 'RFID', 'FACE_RECOGNITION', 'IMPORT', name='attendancesource')
    e_source.drop(op.get_bind(), checkfirst=True)
    
    e_reason = sa.Enum('SICK', 'PERSONAL', 'SPORTS', 'OFFICIAL', 'UNKNOWN', name='attendancereason')
    e_reason.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
