"""implement_teacher_subject_assignment_module

Revision ID: e10dec6a4888
Revises: 3d2cf6d3430c
Create Date: 2026-08-01 13:00:37.071948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10dec6a4888'
down_revision: Union[str, None] = '3d2cf6d3430c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subject_assignments',
    sa.Column('assignment_type', sa.Enum('PRIMARY', 'SECONDARY', 'SUBSTITUTE', name='assignmenttype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weekly_periods', sa.Integer(), nullable=False),
    sa.Column('workload_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'TRANSFERRED', 'ARCHIVED', name='assignmentstatus'), nullable=False),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('maximum_students', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'class_id', 'section_id', 'academic_year_id', name='uq_tsa_composite')
    )
    op.create_index(op.f('ix_teacher_subject_assignments_academic_year_id'), 'teacher_subject_assignments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_class_id'), 'teacher_subject_assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_id'), 'teacher_subject_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_school_id'), 'teacher_subject_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_section_id'), 'teacher_subject_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_subject_id'), 'teacher_subject_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_teacher_id'), 'teacher_subject_assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_tenant_id'), 'teacher_subject_assignments', ['tenant_id'], unique=False)

    # Bulk seed default teacher subject assignment permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Teacher Subject Assignment", "code": "teacher_subject_assignment.create", "description": "Assign teacher to academic subjects", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Teacher Subject Assignment", "code": "teacher_subject_assignment.read", "description": "View teacher subject assignments mapping", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Teacher Subject Assignment", "code": "teacher_subject_assignment.update", "description": "Modify teacher subject assignments mapping", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Teacher Subject Assignment", "code": "teacher_subject_assignment.delete", "description": "Soft delete teacher subject assignments mapping", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_subject_assignments_tenant_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_teacher_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_subject_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_section_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_school_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_class_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_academic_year_id'), table_name='teacher_subject_assignments')
    op.drop_table('teacher_subject_assignments')
    
    # Drop enum types manually
    e_type = sa.Enum('PRIMARY', 'SECONDARY', 'SUBSTITUTE', name='assignmenttype')
    e_type.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('ACTIVE', 'INACTIVE', 'TRANSFERRED', 'ARCHIVED', name='assignmentstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
