"""implement homework module

Revision ID: e2227f71934f
Revises: d1351c0630e0
Create Date: 2026-08-01 17:32:02.143197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2227f71934f'
down_revision: Union[str, None] = 'd1351c0630e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', name='homeworkpriority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='homeworkstatus'), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('ai_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_subject_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('timetable_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_assignment_id'], ['teacher_subject_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homeworks_academic_year_id'), 'homeworks', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_homeworks_class_id'), 'homeworks', ['class_id'], unique=False)
    op.create_index('ix_homeworks_due_date', 'homeworks', ['due_date'], unique=False)
    op.create_index(op.f('ix_homeworks_id'), 'homeworks', ['id'], unique=False)
    op.create_index(op.f('ix_homeworks_school_id'), 'homeworks', ['school_id'], unique=False)
    op.create_index(op.f('ix_homeworks_section_id'), 'homeworks', ['section_id'], unique=False)
    op.create_index('ix_homeworks_status', 'homeworks', ['status'], unique=False)
    op.create_index(op.f('ix_homeworks_subject_id'), 'homeworks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_homeworks_teacher_id'), 'homeworks', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_homeworks_teacher_subject_assignment_id'), 'homeworks', ['teacher_subject_assignment_id'], unique=False)
    op.create_index(op.f('ix_homeworks_tenant_id'), 'homeworks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_homeworks_timetable_id'), 'homeworks', ['timetable_id'], unique=False)
    
    # Bulk seed default homework permissions
    import uuid
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    permissions_data = [
        {"id": uuid.uuid4(), "name": "Create Homework", "code": "homework.create", "description": "Allows creating homework assignments", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Read Homework", "code": "homework.read", "description": "Allows viewing homework assignments", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Update Homework", "code": "homework.update", "description": "Allows updating homework assignments", "created_at": now, "updated_at": now},
        {"id": uuid.uuid4(), "name": "Delete Homework", "code": "homework.delete", "description": "Allows deleting homework assignments", "created_at": now, "updated_at": now},
    ]

    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('id', sa.Uuid),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True))
        ),
        permissions_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homeworks_timetable_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_tenant_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_teacher_subject_assignment_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_teacher_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_subject_id'), table_name='homeworks')
    op.drop_index('ix_homeworks_status', table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_section_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_school_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_id'), table_name='homeworks')
    op.drop_index('ix_homeworks_due_date', table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_class_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_academic_year_id'), table_name='homeworks')
    op.drop_table('homeworks')
    
    # Clean up permissions
    op.execute("DELETE FROM permissions WHERE code LIKE 'homework.%';")
    
    # Drop enum types manually
    e_priority = sa.Enum('LOW', 'NORMAL', 'HIGH', name='homeworkpriority')
    e_priority.drop(op.get_bind(), checkfirst=True)
    
    e_status = sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='homeworkstatus')
    e_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
